### ISSUE TITLE
[BUG] Spaceship Core Reverse Axis toggle broke

### ISSUE THREAD

**Issue by daOyster** [tsunamayo/Skywanderers#1050]
### Short Description of the issue:

With the addition of being able to pick the orientation of a spaceship in the spaceship core, a new bug has been introduced. The reverse axis toggle doesn't just reverse the orientation of a ship, it also flips it which doesn't allow you to actually reverse the forward direction of a ship without also making it fly upside down.

### Steps to reproduce the issue:

1. Load into any save.
2. Place a spaceship core on any ship.
3. Press 'f' on the core to open up the ship menu
4. Check the reverse toggle on the top of the menu.
5. The orientation of the ship is reversed as expected but also flipped upside down.

### Environment
- Skywanderers version: Pre-Alpha 18w51a
- Graphics Card: Geforce GTX 970

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
Before being reversed:
![image](https://user-images.githubusercontent.com/1314048/50315235-efad9900-047f-11e9-9075-7506491974b3.png)
After checking the reverse option, notice the ship is now also upside down:
![image](https://user-images.githubusercontent.com/1314048/50315241-f3d9b680-047f-11e9-9518-a5281e9cbb94.png)

 [output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2700833/output_log.txt)

**Comment by ZachZent** [comment]
Since this bug (?) is here, I may as well add a little suggestion to it

To be frank, changing the alignment is a bit of guesswork. Rotate around forward, switch axis, and reversed isn't very clear what will happen until you click around a bit. In any case, multiple people on the Discord have had a bit of trouble working with it with one case where he couldn't rotate it to where he wanted.

So I "edited" two variants of the interface. The first one doesn't change the configuration. All it does is add an arrow where it will rotate when you hover over the button. Simple yet effective. The second one is my personal favorite. It is as comprehensible as it gets. I don't think anyone will get confused when working with it without sacrificing anything to the game as a whole. Or go full out and combine both of them :D

![test4](https://user-images.githubusercontent.com/36980446/50381095-f03e5f00-063a-11e9-9f55-6d6101530853.png)

It may seem like a small thing, but simple and understandable controls is a major benefit even if it is a small change. Confusing controls like these leave an overall negative impression for new players. Imagine starting up Minecraft for the first time and the movement controls were Move X, Move -X (move left and right, A and D.) Sure you can get used to it, but every little inconvenience will drive people away. The git gud response is rarely the right one. There are other weird setting descriptions, but I will leave that for later

**Comment by tsunamayo** [comment]
Okay I will see if I can reproduce.
Yes I agree it seems very confusing for newbie. The trick is to first align forward, then reverse, then align up vector.
What I will do:
 - by default use orientation of joystick brick. So newbie wont have to care about this.
 - see if a custom override is needed, with an options to override. 
 - Then I can change the setting a bit. I will display X Y Z axis, then I will add dropdown for Move Forward and up vector where player will select + - Axis. That way it would look like less of a guesswork.
Cheers

**Comment by tsunamayo** [comment]
This feature has been removed, so bug no longer apply. Now orientation come from the yoke orientation. Cheers
