### ISSUE TITLE
[Experimental] 19w03a -Wipe- Spawn wrong.

### ISSUE THREAD

**Issue by JRL101** [tsunamayo/Skywanderers#1077]
### Short Description of the issue:
Getting spawned in rings of the planet but no sign of the habitat ring.

...

### Steps to reproduce the issue:
Wipe game from //appdata//
Wipe game from Steam game files/common
re-install
load game 
...

### Environment
- Skywanderers version: 19w03a
- Graphics Card: GTX1080

### Additional information:
_(Screenshots, Videos, Error logs, Related issues)_
![image](https://user-images.githubusercontent.com/33255536/53287519-38ebd300-37b8-11e9-81bf-6789f209f9e6.png)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/2896870/output_log.txt)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by LazyZarra** [comment]
Additional info:
I am of the believe that it has something to do with loading of world objects (ring, craft, mechs and hovers).
I was playing release version 18w20a and switched over to experimental version 19w03a.

My save game position is correct (judging by the celestial body, the rings, and the nebula's in the distance), but the ring, buildings and other things that usually greet me were missing.

[output_log 19w03a.txt](https://github.com/tsunamayo/Skywanderers/files/3041545/output_log.19w03a.txt)
In the log, past line 206, you'll see that its not finding the required save files.

**Comment by JRL101** [comment]
Unlikely its got something to do with loading objects, since its putting me in the same place every save wipe. Either there's an incorrect spawn location or the tutorial ring world file is missing from the installation.
It's looking like old saves are even missing the ring world or i've been placed in the same location as that screenshot.

**Comment by LazyZarra** [comment]
just for the sake of argument, I tried what you did. wiped the appdata, wiped the install folder.
I got the same starting placement as you based on the screenshot you provided. 
then I saved the game and downgraded to 18w20a (the normal non-experimental release). and loaded up that save I made in version 19w03a; the location remained the same. but I'm inside the starter building on the ring. if I exit the building and fly up high enough, I see the exact same gas giant with rings. So yes I do believe it is a loading issue as evident from the output_log I posted.

The objects that version 19w03a couldn't load due to a 'no save file found' error, as mentioned in my output_log are actually part of the game's install ( \Steam\steamapps\common\Skywanderers\Skywanderers_Data\StreamingAssets\PlayerEntities ) which include the ring, buildings and example entities. The mention save files do in-fact exists in both versions, why it says otherwise is beyond me.

Normally you would be able to teleport to existing entities using F7. in 18w20a there are several. in 19w03a there are none which further supports my findings.

**Comment by JRL101** [comment]
The object is the world ring, and all the old entities. The load issue is the world file, not an actual object in the game. 
Its the same planet yes. Its the same system yes. 
A new world on the old version will put you in the old world ring tutorial area, because its part of the installation files.
A new world in the new version isnt loading the ring because the ring world file is missing. So it has a load error. 
The file isnt there and it cant load it. The world file is gone in the updated version or not linked. 
Not that it knows the file is there but not loading the assets.
The files left in the folder are old versions when it updates, so its not a load error is a missing file causing a load error.

**Comment by tsunamayo** [comment]
Yes for now Torus are gone but they will be back with a vengeance soon! Cheers

**Comment by tsunamayo** [comment]
Torus is back! Thanks
