### ISSUE TITLE
[RotC] New Cockpit Glass' Overhang Looks Cool, But is Difficult to Build Around

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1131]
So, I like the shape of the new cockpit glass, it looks pretty neat, especially on a Goblin-sized ship. However, the way it is bigger than the block it is placed in has caused some frustration for me. 
For one, it sits half a brick outside the block, making it difficult to add bricks around it that are flush with the glass. In this picture, I'm trying to have a triangular piece sit up against the glass to make it look like it is shaped differently.
![20190527211754_1](https://user-images.githubusercontent.com/26584892/58446915-36a35880-80c8-11e9-89e9-c82264388dd1.jpg)

Secondly, it causes a hinge to stop when trying to have the glass open. In this picture, I'm trying to have the hinge open the glass up and forwards, but the lip on the glass keeps it from rotating any further.
![20190527212020_1](https://user-images.githubusercontent.com/26584892/58446923-3e62fd00-80c8-11e9-9ebe-bd5c38dc098a.jpg)

In order for it to be easy to build with, I think it should fit completely inside the block.

Also, the hitbox needs to be empty inside so that we can fit stuff in it and be able to walk through it.

**Comment by tsunamayo** [comment]
Yes I need to improve it. Cockpit are for some reason a nightmare to work with. For the size I will make them rescale at a 0.25cm threshold, but with a min size of 1m (otherwise it wont look okay), I just need to code that min size option, it wont be difficult. For the collision with the hinge I need to investigate a bit more. For the collision inside unfortunately for now it is expected until I upgrade the collision algo of the game. Thanks!

**Comment by Womble-TC** [comment]
You could always have some brick sized canopy peices to solve the problem for now (maybe just some basic slopes, squares and corners)

**Comment by Womble-TC** [comment]
For reference, pieces similar to these perhaps 
![image](https://user-images.githubusercontent.com/29961381/58496893-ab32d180-8172-11e9-93f9-2128deacfcd3.png)

**Comment by tsunamayo** [comment]
Yes I will add those bricks back for sure.

**Comment by tsunamayo** [comment]
I made it smaller to fit inside a 1m box. I dropped my idea of 0.25cm increment, there would be too much pb coming from it. 
For the hinge I think it is an issue linked to the hinge itself not much of the canopy. Hinge are extremely hard to design, it is all about where you put your axis and how you position the new grid.
Anyway I got it working, you need to have a small void at the front so it can open. Otherwise puting the hinge on the top-rear of the canopy should be less tricky as another option.

![image](https://user-images.githubusercontent.com/6604318/58534796-2f469100-8227-11e9-87ed-4180e37caaaf.png)

![image](https://user-images.githubusercontent.com/6604318/58534839-4f765000-8227-11e9-9feb-a4c103766a7f.png)

Cheers

**Comment by tsunamayo** [comment]
Btw I am open to any suggestion on the hinge side, like what you think would me the most useful and easier to understand.

**Comment by ProPeach** [comment]
The hinge design featured in Experimental was a great one, what made  you want to change from that? Having the axis of rotation on the corner of the block is most helpful I think, with the current one the slight half brick offset can be frustrating. Plus, this one only rotated 180 degrees rather than a potential 360 from the previous design

**Comment by tsunamayo** [comment]
So the main reason was the previous one was a big hack, and it was causing many problems... I decided to stop doing all these hacks, the price paid long term is just too high. 
Current one axis is offset vertically. To rotate it more I could offset it also horizontally, it could rotate 270 or more.
For that reason I might have to change the slider also, I will do a big block one and a small brick one. Only two there are, no more, no less, a 1m one and a 0.25m. Same for systems, weapon ect.

**Comment by Senakysam** [comment]
Thanks for the canopy change, that should let me finish up the detailing I wanted to do around it on the new ship. 

As for hinges, I think having the center of rotation offset by half a brick makes things a tad awkward. I can probably work around it, but it will take some messing around.

**Comment by ProPeach** [comment]
I'd definitely prefer a non-offset axis of rotation to additional range of motion. The sliders in RotC clip into blocks a little to make sure that they sit flush with the blocks beneath it, this might also work with hinges

**Comment by tsunamayo** [comment]
Yes that clipping thing is a nightmare to deal with, thats why I changed to hinge design and why I will also change the rail. There is just too much issues linked to that. I will make several design on paper, I will then open a separate thread and we will discuss then test that out. I keep you posted, thanks for the feedback!
