### ISSUE TITLE
Deselecting Build Items

### ISSUE THREAD

**Issue by jammeo** [tsunamayo/Skywanderers#1171]
### Short Description of the issue:
I have just opted into the game  and the predominant issue I encounter is the inability to deselect a item once you have equipped it to toolbar. For example I selected a rocket launcher in the toolbar with a hotkey e.g. 1.  after placing a few blocks of this I try to add another item on the toolbar. The previous item (rocket launcher) is then automatically added to any hotkey slot I press on 1-9. Having a button to just cancel anything your doing and clear your build hand would make it a lot easier to build items.

Best Wishes

James
...

### Steps to reproduce the issue:

...

### Environment
- Skywanderers version: 
- Graphics Card: GTX 1050

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by tsunamayo** [comment]
Hi, I cant reproduce that issue, I am not sure to understand correctly the test case.
Is it something you reproduce 100% of the time?
Could you please give me a simple test case, like:
1) open codex .
2) drag rocket launcher to slot 1)
3) place rocket launcher a few time
4) open codex
5) place another item instead of rocket launcher

Thanks a lot for your help!

**Comment by tsunamayo** [comment]
If I understand this correctly this issue should have been fixed #965 . Thanks!
