### ISSUE TITLE
[Bug] Mass disparity between blocks and bricks

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1233]
### Short Description of the issue:
Bricks are much more massive than blocks, this makes it so that a ship made with blocks, will be faster than it's equivalent in bricks.
...

### Steps to reproduce the issue:
I made two example ships, one with one block, and another with the equivalent in bricks.
As you can see, the block one has a mass of 35kg, and the brick one 154kg.
If you try to fly them, the block variant has a much higher acceleration than the brick one.
...

### Environment
- Skywanderers version: 23b
- Graphics Card: AMD RX 580

### Additional information:

[Skywanderers Mass Test Blueprints.zip](https://github.com/tsunamayo/Skywanderers/files/3261347/Skywanderers.Mass.Test.Blueprints.zip)

**Comment by tsunamayo** [comment]
Yes, so actually it is so that people use block whenever they can. But I will do a pass on mass when I will dig deeper into balancing once we have proper gameplay. Thanks

**Comment by AfterRebelion** [comment]
I can see why they need to be a little heavier, but right now the rate is insane. One block is 9kg, and a brick 2kg, so a 1m^2 brick (4x4x4 bricks) is 128kg, more than 14 times heavier.
This makes it so shuttles and small ships can be much slower than much more bigger ships.

Since there are no proper gameplay, this really can wait, but I wanted to express these numbers.

**Comment by ProPeach** [comment]
I can definitely see why you'd want to dissuade players from spamming bricks for performance, but I don't think that increasing their mass is the way to do it.
I propose that bricks are the same density as blocks, but they perform worse in other areas. If bricks suffered from a small (1-10%) nerf to their rate of heat dissipation and armour, the larger you build a  brick ship the more you'd potentially gain from building with it blocks.
So out of a pair of otherwise identical ships, the brick ship will perform worse than a block based ship the larger these ships are as shown in the graph. Note the period in the graph where there is little difference between the brick and block ship is limited to small scales, where bricks are most useful.
(Sorry for the crappy sketch!)
![image](https://user-images.githubusercontent.com/27857711/59152167-ccc76f00-8a36-11e9-9e23-e1334f1df2c3.png)

This is a small enough nerf that fighters/other small ships won't be very heavily affected, but the larger you build the ship the more the player is persuaded to use blocks.
Furthermore, this won't hurt ships with lots of beautiful brick interior work by increasing their ships mass by a larger than necessary amount.

Hope this helps o/

**Comment by ExodistSKY1** [comment]
I support ProPeach's proposal on this matter. It still allows for fighters to be a viable asset in the game (most other games do not) and yet it still deters builders/players from spamming a large ship with strictly bricks!

**Comment by Dwarf-LordPangolin** [comment]
I also think ProPeach's suggestion is a good balancing mechanic.

I agree that some method needs to be found to encourage players to use blocks whenever doing so is viable, but fighters really need to be built predominately out of bricks; otherwise they end up looking a bit too chunky. The current mass of bricks means that larger ships not only have more hull points, more powerful shields, and more powerful weapons, but they are also faster. As the current build stands, there is no real reason to build small craft like fighters.

**Comment by AfterRebelion** [comment]
Related https://github.com/tsunamayo/Skywanderers/issues/1532

**Comment by tsunamayo** [comment]
Okay we now have a new mechanism to make brick more interesting, please see #1571 for feedback. Thanks!
