### ISSUE TITLE
Button sends low/off signal, toggles 'on' and 'off' like switch

### ISSUE THREAD

**Issue by Majikmonster** [tsunamayo/Skywanderers#1263]
Buttons will send a 0 signal when they are 'off'. This is the same behavior as switches.
...
Place a button and connect it to other logic/system.
Press button once to toggle, press again to toggle opposite state.
...
- Skywanderers version: 19w23d
- Graphics Card: Nvidia GeForce GTX 1060
...
![20190613132405_1](https://user-images.githubusercontent.com/51390907/59454046-3d77de00-8ddf-11e9-943c-ff4cede79c76.jpg)
![20190613132413_1](https://user-images.githubusercontent.com/51390907/59454052-3fda3800-8ddf-11e9-87b9-b3254d0d7cd0.jpg)
...
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3287358/output_log.txt)

**Comment by tsunamayo** [comment]
Hi, this is actually the expected behaviour, what would like to see instead? I could make someting that send 1 for like 0.5 sec and then revert back to 0. Cheers

**Comment by talrey** [comment]
I think the confusion here is that this brick is called a "Button" in the codex, and has the description "A simple button that will send a 1 each time it is pressed." ... but the behavior it exhibits is more like a Switch, which toggles each time you press it.

If you change the name and description to match the Switch then the behavior will make sense. If we have a diagonal "Button", it should behave like the flat (white brick) Button and only send a 1.

This is more of a request than more bug details, but maybe we could have a Button brick that's diagonal like this one, but instead of saying "on" and "off" like a Switch it just blinks to indicate it's been pressed and sends a 1? Then again that's not really necessary, since the flat brick Button doesn't have any visual feedback either.

**Comment by Majikmonster** [comment]
I was not aware of that. Thanks for clarifying. I would indeed like to see a pulse function for an activator of some kind, as described above.

**Comment by tsunamayo** [comment]
So for the button I still need to convert the older one, it dont make any sense.
Just sending a 1 pulse dont make any sense in the new logic system, unless you feed it in a laser / switch (but I want to work on those)
On the other side I could send a short timed pulse: send 1 for 0.5 sec then go back to 0, if you think it could be useful I could make it.

**Comment by talrey** [comment]
If you're going to change them, would it be possible to make it so that they send a 1 pulse when the player activates them, and only send a 0 pulse when the player lets go / looks away? Being able to "hold" the button would be really useful for things like rapid-firing weapons, or holding a door open for another player.

**Comment by tsunamayo** [comment]
Yes sure, I will put something like max(0.1s, player input). Gonna have to change a few things as for now it activates on key release. Thanks

**Comment by tsunamayo** [comment]
Okay I have change the way the button work. It is now a push button. Cheers
