### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CGS-Thomas-Fahey** [tsunamayo/Skywanderers#1282]
Short Description of the issue:
corruption on Discord Server 
...

Steps to reproduce the issue:
Less corruption
and UN ban me
...

Environment
Bulling 

Additional information:
PS: do not ban me from this to pls

**Comment by CGS-Thomas-Fahey** [comment]
Sorry
All the stuff on the server and this was my brother
i apologise for it all sincerely and request that you UN bun me

**Comment by CGS-Thomas-Fahey** [comment]
from the server pls

**Comment by CGS-Thomas-Fahey** [comment]
this is what it said

Banned from Skywanderers
You were banned from Skywanderers
Reason:
No reason specified
Banned until
Indefinitely
Banned by Xerma#2366 (130867391562252288)•Today at 5:10 PM

**Comment by CGS-Thomas-Fahey** [comment]
i am sorry for what my brother did he was trying to annoy me

**Comment by CGS-Thomas-Fahey** [comment]
my account is
Archer_609
#2961

**Comment by CGS-Thomas-Fahey** [comment]
sorry 
again for what my brother did

**Comment by ZachZent** [comment]
Look, I told you what you did wrong. Joking is one thing, but what you didn't wasn't a joke. That sort of action to a new member is not looked well upon so you were muted. The bot (hail jimbo) would have unmuted you when whatever time Xerma set was over. You left and joined like 10 times and didn't show any sign of stopping so you were banned.

More then that, this is not a place to voice your protest about a community run Discord. This is for finding bugs about the game. Next time learn your lesson, but after this I wouldn't expect to be invited back any time soon

**Comment by Tommyg930** [comment]
Though I'm not of the moderation team, I think we've all seen this story before:

Guy comes in, acts the mickey thinking no one can touch him. woops! someone can touch him and takes away his ability to interact for a bit. he dodges punishment somehow and continues on. then gets banned which can't be dodged. Then starts pleading that it wasn't him but that it was his brother (Which can't be verified because, text chat) out to get him because you stole his sweet roll or some non-sense like that. 

All a likely story if a bit convenient. And anyone who grew up with siblings has quickly learned to never leave stuff logged in or running because said siblings will mess with it just because they can.

Regardless if your story is true or not, the blame for either case can only be laid at your own two feet.

**Comment by CGS-Thomas-Fahey** [comment]
can i ever be added again

**Comment by CGS-Thomas-Fahey** [comment]
like in a month

**Comment by ProPeach** [comment]
No

**Comment by CGS-Thomas-Fahey** [comment]
sad
