### ISSUE TITLE
Clipping must stay (Phantom Blocks)

### ISSUE THREAD

**Issue by DioTheCreative** [tsunamayo/Skywanderers#1287]
Clipping must stay. I understand what it means to game balance, but this was really what caused me to even be interested in this game. I'm saddened to see that this was never meant to be considered in the game, the ships that were made were so amazing. I even used a small amount of it in my own ship, I doubt it will ever look as good without that small bit of detail.

Please consider adding this as huge feature, there are many ways it can be done without breaking balance. Already all you would need to do is have small blocks not be able to clip into each other, just the larger blocks excluding engines and generators. At worst armor will only have 2X weight and armor in exploit.

Another way this could be done is to add cosmetic Phantom blocks, these blocks don't have any mass or armor. They would allow clipping or passing through large blocks to create details on a ships surface, some may say there are exploits here. Though one would be dumb to assume anything added to a game would never have any exploits. Solutions would be easy to find though:
Lagging the game - Simply add a phantom weight that can't exceed the weight of the ship.
Making ships bigger then they actually are - Make it so phantom blocks can't be place if it makes the ship bigger, and have normal blocks not be placeable on phantom blocks.
Waist of time - This was literally the thing that made me and my friends say this game would totally be worth it.

**Comment by ultrak2k** [comment]
Did you come to the game expecting clipping to last forever in a game that wants survival, and then are angry that it’s being emotes?

**Comment by DioTheCreative** [comment]
Yes I did come expecting that, that's what the game has been advertised on. That's what people were talking about, "Hey look at what you can build!". If the dev wants to make this game a boring Elite Dangerous rip off with a lame building system every other game has fine by me. If your so smart why can't you come up with a way to add clipping or something like that?

**Comment by ultrak2k** [comment]
This game without building has a build system surpassing all others, don’t put the burden of suggestion to add clipping back on me when I along with most other people don’t want it in the game, and the game was absolutely not advertised on clipping, it was advertised around the brick system and later freeform.

**Comment by Xerma** [comment]
![gottem](https://user-images.githubusercontent.com/32974671/59805720-ae276a80-92b7-11e9-8f99-1d653d92d93c.png)

**Comment by ProPeach** [comment]
Clipping of brick and child entities was only ever a happy accident. As far as I know it was never meant to be a feature, nor was it advertised as such. In fact, it's been mentioned in several devlogs as well as countless times in the Discord server that it will be removed.
Yes, it can be great for getting that exact shape you need, but has huge costs in terms of gameplay and balance. You mention that no other game has it, that's because it's completely unsustainable as a feature. With clipping, Volume as a balancing factor becomes utterly useless, it promotes the spamming of child entities (which has been shown to cause enormous amounts of lag), and you open up a whole other level of pvp ship. A ship that utilizes clipping in its build will almost always be superior to one that doesn't which means to stay competitive players _must_ clip.
In regards to your points, "at worst 2x armour" is neither true nor a good reason. Twice the armour on a ship of the same size is a _huge_ difference, and you can easily stack up to 16 layers of brick armour into a one block space with clipping, and infinitely more if you use child entities.
"Phantom" blocks are also not a viable replacement for clipping. What stops people covering portions of their ships completely in "phantom" blocks? A ship could look like a featureless cube yet be covered in windows, turrets or thrusters beneath the "phantom" blocks.
Your method for stopping players "making ships look bigger than they actually are" also wouldn't work out. If you place any block on the exterior of a ship, you by definition "make the ship bigger". How would you check for this in code? You could check for an increase in the overall bounding box, but what's to stop a player building large frame with  regular blocks and continuing with "phantom" blocks to circumvent that?
As for you point about wasting time, Tsunamayo has spent months developing good alternatives to clipping shapes in freeform and more recently stretchy blocks. You can now also build multiple blocks in a 1 block space as long as they don't clip too. Skywanderers has a whole host of unique and interesting build mechanics that no other game has. Clipping was never going to be one of them.

Personally, I also love the way that bricks work now. You can just about clip a small portion of a brick and get that perfect shape without it being totally broken, but I recognize that if the game is going to be successful as an actual _game_ and not just a ship builder, clipping must go. Sorry.

**Comment by ultrak2k** [comment]
And then we never saw him again...

**Comment by tsunamayo** [comment]
Thanks, I understand the frustration over clipping, but that ship has sailed a long time ago...
It was never a conscious decision from me to add clipping, it was more something I didnt really took time to adress at the beginning. But now it is conflicting with way too many stuff and was triggering too many issues and allowing dangerous building practice (mainly children entity spam) so I had to take the hard call of removing it. 
I need to get rid of all the problematic elements like this, it is just too much time to maintain, I will never release the game otherwise if I spend my time on these.
I never advertised around it but it is true that some ship I showed back in the day were making heavy used of it (like the falcon), and this is why I stopped doing ship review once I understood how deep I was gonna change the engine (will do some in the future though).
But why you dont show me what you are building and how I could create legit bricks to achieve similar results (you can book block suggestion also)? My goal is to provide you with alternatives (some are on the way like for doors ect)
Thanks
