### ISSUE TITLE
[BUG] Window canopy block invisible when attached to side of angled blocks

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#130]
When the window canopy block is place in such a way that the glass is adjacent to an angled block, the canopy block becomes invisible when seen from the same side as the angled block. This seems to occur with most if not all angled blocks, not just a select few.

![20171023165131_1](https://user-images.githubusercontent.com/33041786/31915073-c07c069a-b812-11e7-8648-c10bfb75d9f8.jpg)

![20171023165125_1](https://user-images.githubusercontent.com/33041786/31915067-ba268a40-b812-11e7-88a6-3bf7da75ff21.jpg)

**Comment by GoOtterGo** [comment]
Just to clarify, this bug seems to [still] occur when canopy glass is placed behind _any_ partial block, where the 'backside' of the canopy should be not rendered because it's 'hidden', where in these cases it's obviously not hidden. The same block renders perfectly fine on the 'exposed' side. 

Some more examples:

![inked2017-10-28 12_01_36-greenshot_li](https://user-images.githubusercontent.com/4467148/32136970-a116e7bc-bbe5-11e7-8681-c492809e0945.jpg)
![inked2017-10-28 12_01_53-greenshot_li](https://user-images.githubusercontent.com/4467148/32136971-a129ddb8-bbe5-11e7-888e-67e412a96cb9.jpg)
![inked2017-10-28 12_02_05-greenshot_li](https://user-images.githubusercontent.com/4467148/32136969-a1010c9e-bbe5-11e7-8188-640774008fa9.jpg)

**Comment by AfterRebelion** [comment]
This no longer happens, at least for bricks.
![imagen](https://user-images.githubusercontent.com/559819/59036850-61cc3b80-8870-11e9-8e5f-f3c0089b65cb.png)
And you can no longer place blocks in the same blockspace as canopy, so this is no longer an issue in recent versions (19w23b)
