### ISSUE TITLE
[19w24a] Sliders cause FPS drop when in motion

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1304]
### Short Description of the issue:
Sliders cause a noticeable loss in FPS when in motion.

### Steps to reproduce the issue:
Place multiple sliders, then cause them to move at the same time. The effect is more pronounced if the sliders have multiple bricks attached to them. 4 sliders with lots of bricks cause more FPS loss than double or more bare sliders.

### Environment
- Skywanderers version: 19w24a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3342583/output_log.txt)

**Comment by ExodistSKY1** [comment]
I am also having this issue with a single 2m in length slider.    I go from 130FPS to 27FPS  

Version: 19w24a
Graphics Card: GTX 1080ti

**Comment by Majikmonster** [comment]
I have this issue as well. I go from 120<FPS to 20>FPS. As soon as bricks/blocks are added that slide alongside other bricks/blocks, the frame drop is absurd.

- Same game version and graphics card as Pangolin

**Comment by tsunamayo** [comment]
Collision check are expensive and need a big refactor. I didnt saw that bad of a drop on my side, but it depends a lot on how your ship is design (the more brick you have at one place the worse, it is not only whats is on the slider). Could you give me your blueprint so I can check how bad it is? I have a big refactor planned, I started to write the spec, but it would have to wait for after the gameplay look is in place. Thanks!

**Comment by Dwarf-LordPangolin** [comment]
Sure thing; here's the blueprint. 
[100m Merchantman Prototype.zip](https://github.com/tsunamayo/Skywanderers/files/3363607/100m.Merchantman.Prototype.zip)

**Comment by tsunamayo** [comment]
Nice ship! Yes it is because you used a lot of bricks to make your interior.
It will have to wait for the collision refactor, it will be faster but unfortunately things might not move at all if your build is too complex (which is likely in your case).
To give you an idea why, instead of brute force checking each bricks versus each bricks inside two given colliding voxel (which is insane and not at all sustainable, like if you have 20 bricks on each entity on the voxel thats 400 checks!), I will build an enclosing box containing all the bricks of the given voxel, so a single collision check is only required per voxel pair collision.

A couple remark after looking at your build:
I will make built-in blast door. For performance and gameplay reason.
Also the side thruster is not gonna be useful (thrust will be a vector and no longer a scalar, so they wont count and would consume power for nothing).

**Comment by tsunamayo** [comment]
It should be much better now, although not yet optimum. Thanks
