### ISSUE TITLE
[19w24a] Large 90 degree pipe will not place on pipe base

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1305]
Large 90 degree pipe will not place on pipe base

...

-Place pipe base
-try to place 90 degree pipe on the base

![20190630201542_1](https://user-images.githubusercontent.com/45324484/60405262-a77cdb00-9b74-11e9-9331-27d0d4aabacc.jpg)
![20190630201531_1](https://user-images.githubusercontent.com/45324484/60405264-a9469e80-9b74-11e9-81c6-312692dd90e9.jpg)

**Comment by Majikmonster** [comment]
The large pipes act like blocks, strictly obeying the block grid. This is more of a grid issue than a pipe-specific issue. I would like to see them work in tandem, as the nomenclature of these two lends itself to suggest as much already.

**Comment by tsunamayo** [comment]
Yes, the problem is that if I have them place like a brick (which I could), then you place the corner like you want, but then you will want to place a new pipe or pipe corner at 90deg on the extremity. Then you would not be able, grid wouldnot match. I have to also adjust the size of the base to 0.25cm high. I will see how it looks. I could also make a new tech that I need for the 2-to-1 stud like we had before, I need to reflect on the best approach. Thanks

**Comment by tsunamayo** [comment]
I renamed the block to avoid confusion as their are not compatible this way. Thanks
