### ISSUE TITLE
[19w24a] Small Corner Brick on hinge inhibits free range of movement 

### ISSUE THREAD

**Issue by ExodistSKY1** [tsunamayo/Skywanderers#1307]
The small Corner Brick on a hinge will inhibit the free range of movement if built next to the area the child entity on the hinge should clear. 

...

-place hinge
-place a wall to be flush with hinge
-add bricks to hinge to be flush with wall (think ramp)
-add the small corner brick on the end of the ramp to add an angle to it

The small corner brick will not allow free range of movement when the hinge is activated

...

### Environment
- Skywanderers version: 19w24a
- Graphics Card: GTX 1080ti

![20190701005807_1](https://user-images.githubusercontent.com/45324484/60415544-14a66580-9ba1-11e9-9b13-0995b413d1c1.jpg)
![20190701005822_1](https://user-images.githubusercontent.com/45324484/60415548-1839ec80-9ba1-11e9-9d0e-9282e5a9b226.jpg)
![20190701005845_1](https://user-images.githubusercontent.com/45324484/60415552-1a03b000-9ba1-11e9-9dba-2850d781eaf3.jpg)

also brick blocks when stretched past a 2x1 I also had this issue 

![20190701011129_1](https://user-images.githubusercontent.com/45324484/60415590-39024200-9ba1-11e9-90a8-7fa58c47e372.jpg)
![20190701011140_1](https://user-images.githubusercontent.com/45324484/60415596-3bfd3280-9ba1-11e9-95ed-8c7f6f25abda.jpg)
![20190701011210_1](https://user-images.githubusercontent.com/45324484/60415608-3e5f8c80-9ba1-11e9-9e76-6805d10cb66f.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3344198/output_log.txt)

**Comment by Dwarf-LordPangolin** [comment]
I can confirm that this is happening with the "small wedge" bricks when they are placed on sliders as well as hinges.

This container will not slide into the gap:
![20190702223253_1](https://user-images.githubusercontent.com/33041786/60561710-31b27400-9d1a-11e9-98e9-45f664323f4a.jpg)


But it will once all the wedges are removed from it. Note that the wedges on the parent entity are fine, it's just the ones on the slider.
![20190702223651_1](https://user-images.githubusercontent.com/33041786/60561708-2f501a00-9d1a-11e9-89fa-3d0f768fe5a4.jpg)

**Comment by tsunamayo** [comment]
Hi, I tried to reproduce but it is working fine on my side. Could you please send me your blueprint so I can check the issue? Thanks

**Comment by ExodistSKY1** [comment]
It now seems to be working, as i had tried it 10 rimes on both ramps. I will keep trying to reproduce again

**Comment by Dwarf-LordPangolin** [comment]
This bug is still present. This setup works fine like this, moving cleanly to open and closed positions:
![20190718130907_1](https://user-images.githubusercontent.com/33041786/61481294-8c281300-a95d-11e9-8f42-17ad11d6ca1e.jpg)

![20190718130913_1](https://user-images.githubusercontent.com/33041786/61481389-cee9eb00-a95d-11e9-8991-5f192dc45a6b.jpg)


However, once a corner brick is added next to the second hinge on the landing gear, it jams that hinge after it moves once, even though it shouldn't be making contact with it.
![20190718130925_1](https://user-images.githubusercontent.com/33041786/61481721-7830e100-a95e-11e9-92ed-132c0408aa9d.jpg)

![20190718130939_1](https://user-images.githubusercontent.com/33041786/61481728-7a933b00-a95e-11e9-9513-1efacba29912.jpg)

**Comment by tsunamayo** [comment]
This should be much better with the newer collision tech. Thanks
