### ISSUE TITLE
[Suggestion] individual deletion for dragged blocks

### ISSUE THREAD

**Issue by Dictatorputski** [tsunamayo/Skywanderers#1313]
(copied from my suggestion on the website forums)
I really enjoy the draggable block system, and really like how it speeds up construction for large open spaces, decks, walls etc. But a problem i find is that if you wanted to change a small bit of a wall or floor to ,let's say, add a window or a grate, you have to delete and repaint the entire part, which means having to rebuild that entire section around the bit you wanted in it and if you want to make multiple small changes, this can be very time consuming. Therefore i propose a method, such as alt-right-click, to delete individual blocks from these large draggables. it doesn't have to work on hull and blocks that leave irregular pieces such as on wedges but will certainly save time and effort for when large constructions are being built. Thank you

**Comment by Lsutehall** [comment]
I agree, and was going to suggest this myself, although I don't think it should avoid certain blocks. The reason is that stretchy blocks are great for blocking-in big areas of a ship's hull, but on smaller builds you need that space for the interior and systems. Being able to "hollow out" the interior of these large dragged shapes would be very beneficial.

**Comment by tsunamayo** [comment]
Hi guys, thanks for feedback and suggestion. 

Yes I totally get why this would be nice to have this from a building view point, for doing windows and such. The problem is that since I move toward that stretching tech this was something I had to give away. It is either you repeat the block and can delete block one by one, or you get a single stretching block. 
I think the stretching tech is bringing a lot to the table, and is definitely fresh, so I decided to make that move, it was a big investment but it actually made a lot of sense on so many aspect.

As for not being able to carve inside a block, it sucked, but I was thinking that it is still faster than minecraft where you have to put block one by one... So it seemed like not a show stopper to me ;)

On a side not if paint is an issue, I could leave the paint at the same place so you dont have to repaint them. I will try that for a while and I will check if there is any negative impact.
