### ISSUE TITLE
[19w28a] Joysticks on child entities cause orientation issues

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1337]
### Short Description of the issue:
Placing a joystick on a child entity prevents the ship core from getting the correct orientation. Not sure how this _would_ be fixed, so maybe joysticks should only be placeable on the parent ship?

### Steps to reproduce the issue:
Create a ship with a joystick on a child entity, link it to the ship core, then check the core's orientation.

### Environment
- Skywanderers version: 19w28a
- Graphics Card: NVIDIA GeForce GTX 1060 6GB

### Additional information:
![20190708183232_1](https://user-images.githubusercontent.com/33041786/60849074-cac80b80-a1ae-11e9-9478-85a67e9b2576.jpg)

![20190708183242_1](https://user-images.githubusercontent.com/33041786/60849077-ce5b9280-a1ae-11e9-8bce-d3b8bc9d4694.jpg)

[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3370542/output_log.txt)

**Comment by tsunamayo** [comment]
Hum yes indeed. So to fix this I could either:
1) bring back orientation UI for special case.
2) have only joystick on main entity being able to link to shipcore. But you could like a children joystick to a parent joystick to still make what you want... A bit cumbersome but that would work I guess...
Would like to hear your opinion on this!
Cheers

**Comment by Dwarf-LordPangolin** [comment]
I feel Option 2 would probably be best. Determining ship orientation by the position of the parent joystick is a nice, intuitive system that I think new players will be able to handle more easily, and I feel it should be kept. Then, if the player wanted to have a cool sliding joystick or similar they could do that too.

**Comment by khowhl** [comment]
Option 2 is perfectly fine. However the current build doesn't save the link between a yoke on a child entity and the yoke placed on the main ship upon save load.

**Comment by AfterRebelion** [comment]
Just a little insight on the root cause of this problem.
The real reason why this happens is because the child entity is aligned in a different direction than the parent entity, as you can see in this example screenshots.
Parent entity forward axis:
![Parent entity forward axis](https://user-images.githubusercontent.com/559819/61408996-9c021180-a8e1-11e9-8642-658055ed498c.png)
Child entity forward axis:
![Child entity forward axis](https://user-images.githubusercontent.com/559819/61409471-978a2880-a8e2-11e9-961f-6493a91225d7.png)

So even if relative to the parent entity the joystick is facing forward, in the child entity it is facing left, having this as a result:
![image](https://user-images.githubusercontent.com/559819/61409291-395d4580-a8e2-11e9-8ca1-9739b5ccbf71.png)

With hinges there is really not much that can be done, since the can freely rotate, but for sliding blocks, since axis will always remain rigid compared to the parent, it would be good that the were aligned to the same directions.

[Direction Testing Ships](https://github.com/tsunamayo/Skywanderers/files/3403764/Direction.Testing.Ships.zip)

**Comment by tsunamayo** [comment]
Okay thanks for your contribution all, I added the mandatory requirement of having the yoke on the parent entity. But like just said you can always plug your children yoke on the main yoke as you want, the frame of reference being the main yoke. 
I will need to come up with a way of telling the player why he cant do something at one point, as it could prove frustrating. Cheers!
