### ISSUE TITLE
Logic gates and switches

### ISSUE THREAD

**Issue by AfterRebelion** [tsunamayo/Skywanderers#1379]
### Short Description of the issue:
When the output of a logic gate is connected to a switch it doesn't work as expected.
The inputs ignore the logic, and goes directly to the switch, changing it's state.
~~This is a problem as seen in the 2nd example with the new buttons and a OR gate. Instead of just passing a signal when the button is pressed (ON state), it passes the signal two times (One on the ON state, and another one when going back to the OFF state), making the use buttons to change easily the state of a switch impossible.~~ It came a little late to my attention that the 2nd example is not a good one, since that is what happens when directly connecting to a switch. It was when testing ways to make several inputs with the new buttons that this problem became apparent.
On the first example, if you press any of the inputs (The switches on the right) it changes the output, even though a change only should happen when all inputs are pressed (AND gate)

### Steps to reproduce the issue:
Here you have an already built example. 
[[TEST] Logic and Switches.zip](https://github.com/tsunamayo/Skywanderers/files/3411804/TEST.Logic.and.Switches.zip)
To see the problem in action, just press any of the buttons once.

### Environment
- Skywanderers version: 19w29b
- Graphics Card: AMD RTX 580

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_
![imagen](https://user-images.githubusercontent.com/559819/61548610-5adb4000-aa4e-11e9-8226-84f01ff933c9.png)

**Comment by AfterRebelion** [comment]
That is the issue description, but now I will say WHY I want a change.
![imagen](https://user-images.githubusercontent.com/559819/61550724-87de2180-aa53-11e9-8160-8dff4e443292.png)
Basicaly, I want this to work. You should be able to make it so:
You press the button once: The door opens.
You press the button again: The door closes.

This worked _somewhat_ fine before because the button was a reskined switch, but now I can't see a way of making this work.
Right now, what it does is that you press the button it opens, and then it closes inmediately.
[[TEST] Logic Door.zip](https://github.com/tsunamayo/Skywanderers/files/3411933/TEST.Logic.Door.zip)

**Comment by Majikmonster** [comment]
It is true that the button used to work like a switch. After community feedback requesting that function be changed, it now behaves differently. I don't think it's a good move to revert a change that was requested, but I do think that the purely binary logic system needs to be worked around.

What would solve your issue and create more possible application to this binary system is a 'flip-flop' gate, which only responds to a 1 instead of 1 **and** 0 like the switch. Essentially, it would be the switch behavior you are requesting here, in gate form.

**Comment by tsunamayo** [comment]
Hi, thanks for the feedback and blueprint.
So I think there two things at play:
1) "new" (not that new anymore but I will call it like that) logic is made to behave more like traditional electronic system rather than the old pulse base system. Think that gate are now in sync together: in the case of the AND gate, if that AND ouput now become 0, that output will be propagated to whatever that gate is linked to.
2) Switch behaviour to input. Right now the switch will change its state when its input current change value. I am not sure if it is desirable or not. What I propose is to change that to: switch will toggle only when its input change from 0 to 1. So that when going from 1 to 0 it will do nothing, and your door example will work very simply: plug a push button to a switch, then switch goes to the door and that will be it. Tell me if you see any potential drawback to this.
Cheers

**Comment by AfterRebelion** [comment]
That solution seems good, but my example is a simple one, so maybe someone experienced with more complex circuits should give more feedback.

**Comment by tsunamayo** [comment]
Okay I made the change, we will see if some people are not happy about any potential unforeseen consequences. Will be live in 19w30a. Thanks!
