### ISSUE TITLE
Large/Small Sliding Rail (Addon)

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1394]
### Short Description of the issue:
The large sliding rail is not properly labeled in the codex and it also has the same description as the large slider.

Another issue is the addons don't have an animated rail when the main rail is activated.

The small sliding rail description says, "Use this **brick**..."  whereas the small sliding rail addon description says, "Use this **block**..."

If the rail is extended out on an addon and the addon is broken, the rails position is kept until sent back down the rail. Then if the rail is already sliding down an addon and it is broken, the rail continues on to where it would be if the addon was not broken.
...

### Environment
- Skywanderers version: 19w31a
- Graphics Card: GTX 970

**Comment by tsunamayo** [comment]
Okay all issues are now fixed! When you delete the addon it will reajust the position of the children entity. 
On a side note as you use children entity quite a bit, I was thinking of making a children entity tool, tell me what you would think of that:
 - add a children entity tool
 - slider dont destroy the children entity on destroy => children entity is left floating
 - you have to right click with the tool to delete the entity
 - left click and drag to attach to a new slider / rotator to attach to it.

Cheers

**Comment by tsunamayo** [comment]
Will be on 19w31b.

**Comment by Xerma** [comment]
Hmm, I could see that tool being useful in survival since people probably wouldn't want to have to replace the whole thing to get another entity on it. Would that mean people could tactically shoot off child entities? If so would we still be able to repair and bring them back via the repair beam or shipyard?

**Comment by tsunamayo** [comment]
For survival and damage it will be a non destructive, aka the brick will be damaged with a special (mostly black) texture, but would stay there. I kinda have to do this because of the new stretching tech and as the hp / armor tech is voxel grid based, beside it will be faster. Yes everything will be repairable. 
It is just so you dont delete by mistake your child entity, or can change your mind on where you need it ect. I will need to do something in the like of this to swap turret ect.

**Comment by ProPeach** [comment]
This all sounds great especially the turret swapping/child entity copypaste. Can't wait to see it ingame!

**Comment by Xerma** [comment]
After the addition of the addons for rails, I just have to ask again about the possibility of a "speed controller" sort of block that we could also attach to the rail to speed them up or slow them down. I know it has been asked about numerous times but many many people would absolutely lose their minds if we were able to do this. Like for my sphere ship I'll need larger landing gear for it to visually make sense so they'll take a very long time to deploy. It could even get incorporated with monorails down the line

**Comment by tsunamayo** [comment]
Max speed is gonna be limited by the mass of the children entity, so you would only be able to make them move slower. But I can always increase the base maximum speed ^^.
There is two way I could do this: 
1) instead of being able to activate manually a mechanism, you get into a screen with a few settings, including speed.
2) You do this in a sequencer gate.

I dont know if many people like to activate mechanism manually. I tend to think 1) would be better and would allow more options for the future.

**Comment by Xerma** [comment]
Increasing the base max speed could work but what would you think of having the speed booster require power? If you go that route the sequencer, or whatever ends up being the choice, could use a "speed multiplier" where as the speed multiplier increases so does the power cost (at an exponential curve so the faster you want it to move the bigger the price for it)
