### ISSUE TITLE
Serious issue: ships not moving 19w31a

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#1398]
### Short Description of the issue:
Not sure if there was a hotfix, but suddenly ships don't move using WASD. They still rotate, but I can't seem to get any linear propulsion. 

### Steps to reproduce the issue:
- Spawn in a ship to use
- Get into the pilot seat and take control via flight stick
- Try to move in a linear direction with WASD or using SHIFT (also not working)
- Ship doesn't move

### Environment
- Skywanderers version: 19w31a
- Graphics Card: 

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3449749/output_log.txt)

**Comment by ProPeach** [comment]
I noticed that my ships engines had turned themselves off after this update. Luckily all you need to do is connect a switch to them and flip it to get them working again if that's what's happening here.

You can tell if they're on by looking at the thrust values in the tooltip when you look at them.

**Comment by tsunamayo** [comment]
Ha yes sorry ProPeach is right it was one of the fix I made during the system cleanup pass. What happens is now you can toggle system on / off if you want to manager your ship energy balance for example. Problem is those system were build with a default starting state of 0 (which had no impact). Now they are build with a default state of 1, but your old blocks will still be at 0...
I leave that issue here for a bit some people can see it.

**Comment by Rizzo911** [comment]
OK, it makes sense with that description. I think I tried everything else but hooking a switch to it.
