### ISSUE TITLE
[SUGGESTION] Make The Yellow Column More Yellow

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1423]
With the new paints, we don't have a good option for yellow. Right now, it goes from orange, to yellow-green, to green, to a very slightly different green, then to the blues. I propose making column 4 a more yellow color, and making column 5 what column 4 is right now.
![20190918075214_1](https://user-images.githubusercontent.com/26584892/65179244-09383d00-da20-11e9-9e9e-044784cc1af6.jpg)

**Comment by tsunamayo** [comment]
Okay first name are screwed: first row is red (not cherry), second is orange, then yellow, ect. I already nudged the color a bit to get better yellow and less pink / purple, and I forgot to update the name.

Yes working with hue is really funny because of how our eyes works. The funny things with green is that there is the same hue difference between them as for every other color, but we perceive it almost the same. I will fix the green, they are too close to our eyes. You are okay with just one shade of green (when we have 3 or even 4 blue)? 

Also do you think column 3 is yellow or orange? Actually I had a true yellow but it was too pure, so I shifted all the hue by a bit to get a more usable darker more orangy yellow (like we see in real life)

Also regarding the tone I am not sure if you like the current selection, I can shift them a bit as well.
Thanks

**Comment by Xerma** [comment]
![image](https://user-images.githubusercontent.com/32974671/65196790-3e578600-da46-11e9-8613-81185f53526f.png)
If we could have some options like in this image(basically full coverage), with different saturation/value of course, then I think all would be swell

**Comment by tsunamayo** [comment]
So 18 hue instead of 12? I could indeed, it would mess up the color mapping again though. 
My question is: do people really wants 2 shades of purple and 3 pink? Also like discussed a bunch of green seems too much alike. Thanks!

**Comment by Xerma** [comment]
If color mapping is already messed up with the update I don't think it'd be a huge issue per se if it happened again. Depending on how long it takes anyways. And yea having all of the colors isn't entirely needed but I was just using that as an example. I could find a different one if you'd like or even make one

**Comment by tsunamayo** [comment]
Okay we now have a new color palette, yellow is a bit more yellow and less orangy. But a pure yellow doesnt look good, it have to be a bit orangy. Cheers
