### ISSUE TITLE
[Bug] Can't place block on hinge/rail

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1429]
You can't place any block on the small hinges or small rails. You also can't delete blocks such as glass that were already on the hinge/slider before the update. I hope this is just a bug as it is quite hard to make a cockpit for a small ship without a hinge or slider.

**Comment by Senakysam** [comment]
I believe it is intentional that only bricks can be placed on the small child entities. As for the cockpit glass, I had to delete it then reload the world to make it work. After that I had no issues.

**Comment by tsunamayo** [comment]
Yes this was intentional, the rational from the tech / UX side being that the position in which you spawn the children grid seems arbitrary and hard to understand (and is a pain to code). Like you could spawn the origin right on the block, or align to the parent entity, or else. It was especially tricky and frustrating for hinges. At the end I figure that preventing that was the most elegant way to "solve" that problem...
But you should be able to delete the blocks - so I will fix this.
Also I want to make canopy / windows bricks based, so you have more flexibility. I will do another pass on them.
Thanks

**Comment by ZachZent** [comment]
I see. Though I would wish it to be the other way, I now understand why this is. Canopies and glass should be the exception or some other system in place to allow them to move. As of now, you can't make canopies for small ships that open and close.

**Comment by Senakysam** [comment]
Are you sure there is nothing colliding? I have canopies on a brick hinge and a brick slider with no issue.

**Comment by ZachZent** [comment]
It wasn't earlier. It was only working on the old style hinge and the rotator. It is working now and I got the explanation so ill close the thread
