### ISSUE TITLE
[BUG] Turrets Not Working

### ISSUE THREAD

**Issue by Senakysam** [tsunamayo/Skywanderers#1477]
When linking up a turret core to the rotors and taking control of it with a yoke, it doesn't move at all. 

Version: 19w40b

**Comment by Xerma** [comment]
I'm having a similar issue but oddly enough the turret won't use the vertical axis at all. Plus sometimes the horizontal axis gets stuck and freezes for a little while.
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/3719736/output_log.txt)

**Comment by tsunamayo** [comment]
Okay so be sure what mode you are using? I should make it clearer somewhere, maybe in the turret UI...
a) raw mode; if you use a camera or your seat is on the turret, then mouse movement is directly mapped to the turret. You need to assign horizontal / vertical setting in the rotor for that.
b) tracking mode: you look somewhere and the turret will catch up, or used with a target computer (not your case then). In this case you also need to link a laser so that the turret understand in which direction it is supposed to align itself.
Cheers

**Comment by ZachZent** [comment]
I've had the same issue. After breaking the turret core and relinking them, It worked again

**Comment by Senakysam** [comment]
Haven't had any luck with breaking the core and relinking things. Here's the ship I'm building that the turret isn't working on. Chair and controls are on top, turret is on the bottom.

[Corvette01_WIP07.zip](https://github.com/tsunamayo/Skywanderers/files/3720131/Corvette01_WIP07.zip)

**Comment by Senakysam** [comment]
Okay, so I was unaware that you also needed to link the turret core to the laser. It's working now.

**Comment by ZachZent** [comment]
Question Tsuna, how do you set up a turret to be controlled by AI and not the player? Or is that not in the game yet

**Comment by tsunamayo** [comment]
Yes for sure I need to explain this more, I want to add some help and feedback inside the turret core, and then add some in-game overlay error message so the players knows there is something he needs to fix.
So to get an auto turret you need to plug a target computer inside the turret core. Then it should works in AI whether you fly it or another AI flies it.
