### ISSUE TITLE
[Suggestion] Damage Decals

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1482]
There has been some confusion in the Discord if this idea is the plan going forward, just mentioned as an idea, or just an idea in the community. So just in case it is the second or third, here is the idea for improved damage effects.

I dislike the current block damage look. It feels separated from the rest of the ship and other damaged blocks, no variety in the look, and a bit odd when you damage engines and other systems getting the same damage texture. Disconnected uniform splotches. At least the old cracked block damage look connected with other blocks to make large amount of damage seem connected.
![image](https://user-images.githubusercontent.com/36980446/66692611-ee3e9e80-ec54-11e9-804d-c5736c4be5fd.png)

Instead of the blocks themselves having a damaged look, the idea is to use decals. Damage decals would be placed on the surface of a block upon weapon impact. Size of weapon results in a single brick decal which will despawn quickly to block size and larger decals that only despawn after repair. Decals also allow for different looks depending on the weapon. Scorch marks, bullet holes, laser burns and so on. In the future when more weapon types are added by development or by modders, an accompanying decal can be added in addition to the weapon. Say a flack weapon is added, its decal has small impacts over a wider area. Block destruction would stay mind. Unlike the uniform splotches of before, many simple decals can be added even for one weapon type for the currently missing variety. 
![image](https://user-images.githubusercontent.com/36980446/66692658-61e0ab80-ec55-11e9-8102-35c00e1217d0.png)

**Comment by tsunamayo** [comment]
So actually there is a bug, there should be a grill pattern not just the black texture.
But yes it dont look 100% right, but the goal is to give an idea of the block HP, not to match whatever damage type the block received.  The shape of the hit is basic and limited because I use parallax mapping, so I cant have concave angle...
But I also want to add more localized damage like you shown, for aesthetic / immersion purpose.
I keep you posted when I fix the issue, so at least you can judge the way it was meant to look.
Thanks

**Comment by tsunamayo** [comment]
Okay I fixed the issue, will be in 19w43a (hopefully today). So instead of being black you see a grid pattern beneath. But it still looks too squary I agree (I am limited by the parallax tech...) Thanks
