### ISSUE TITLE
Suggestion - Add a temporary heat dissipation and HP value to Bricks 

### ISSUE THREAD

**Issue by Garrett-C** [tsunamayo/Skywanderers#1489]
So I know you aren’t focusing on brick ships yet and want to balance the block ships first. However this does leave brick ships in a state where you can’t even place a system block on them without them exploding. Would it maybe be possible to add a temporary value just to allow people to still play around with brick ships? Wouldn’t need to be extremely balanced for now because you can explain that it is just a temporary value. One suggestion would be just having the bricks use the block values/64 or something along those lines to have them be roughly proportional. Of course this can be thought out more once you look at balancing them. But for now it would be nice to to have brick ships blowing up, just because they are brick ships.

**Comment by tsunamayo** [comment]
Unfortunately I cant really do this, because the logic is voxel based. But okay your ship explode, but you can still work on it after right? You want to be able to drive it right? 
Cheers

**Comment by Garrett-C** [comment]
Once it blows up you go into the weird pixel reality but I imagine that is something that has been reported and is being worked on. 

Flying the ship is certainly nice yeah. Even just being able to put blocks or systems on without it blowing up though would be nice. As it stands currently bricks are just pointless to use in builds. which is a shame because most of the interesting shapes are bricks. 

I do appreciate that you want to get block ships right first but I do feel that even block ships will use a fair amount of bricks to detail them etc so them having some heat effect and hp would still be a part of larger ship balancing. Could also give greebles some extra application because they would give you a small boost to the HP/cooling.

**Comment by tsunamayo** [comment]
I dont think it was reported, if you could give me a test case that would be cool!

Like said before this would never be a true solution, as brick ship would be still at a massive disadvantage (if brick are at 1/64% of a block) and you would come to me asking to buff them, or reduce system heat to allow brick only ship ect, so it is just moving the problem a bit. And the tech just dont allow it. 
So I will take another approach, typically with a threshold or with a log function of the size, and have them disrupt combat flow with speed and maybe tactical weapon. But I need to have a basis for the standard / gameplay progression ship first.

**Comment by gmunga5** [comment]
Oh it's pretty odd that the weird pixel realm hasn't been reported. I will try and get some data on that for you when I can.

It would be nice if there was some way to build and fly a brick ship without it exploding. Even as a really temporary solution. At the moment most of the useful shapes and the likes are bricks so you are very limited on ship design with blocks. I do understand that you want to focus on the block side first and while I do think that is a slightly troubling approach because balancing things in isolation is only going to make it tough to balance them together. I do still understand where you are coming from.

However this does just mean most of the games building tools are currently useless. Which is a shame.

**Comment by tsunamayo** [comment]
Actually I just manage to reproduce this bug a few hour ago.
Now what shape / tool are you referring to? There is the same 5 basic shapes for bricks and blocks. 

Anyway I will try to come up with something, but could you please agree on the following:

 - a brick only ship of a medium size (say 50m) is gonna be at a disadvantage compared to a block ship. Whether we use my system or your system (brick scale proportionally, aka 1/64%). Because if the brick ship wall are 0.25cm thick and block ship are 1m it is gonna be a big difference at the end. 

So you are gonna come back to me asking to nerf block / boost brick, which would equate to push player to use brick instead of blocks, which would be shooting myself in the foot performance wise. I still havent seen any counter argument to that. 

Also I wanted to have builder / tester to focus on gameplay balance and leave aside micro detailing for a bit - but of course gameplay is limited atm so it is not really interesting. But I would really really appreciate some block based / system oriented blueprint, that is quite vital to me at this stage.

Cheers

**Comment by gmunga5** [comment]
Yeah I agree with your point there to do with a medium ship made of blocks will be stronger than one made of bricks. Which makes sense because a ship with a 1m thick hull of course will be able to take more shots than one with a 0.25m thick hull. That's part of the reason why I think it's important to consider the two systems together. While I understand your desire to focus on one instead of the other it means you are going to have to go back and completely rework the block system once you try to work bricks out. 

Unless you went with a SE style system where you have different block/system scales i.e Large and small where you are limited to bricks or blocks. You are going to have a lot of interplay between the two systems So balancing one while ignoring the other feels like a strange way to do it.  

I do see your concern about bricks being more powerful than blocks if a brick had the same stats as a block and how this would influence building in a way that would be damaging for performance. So here is another suggestion for the values. Why not make Bricks 1/64 - x so that a full block of bricks is slightly worse than the equivalent block. Yes this is a bit odd logically but could be justified some how by talking about structural integrity or something etc. One point also to ask is does the slope have the same properties as the block?

At the end of the day I understand what you are trying to do by getting a basic balanced combat system done so you can add a little bit of game play. However I do feel that by approaching it that way you are potentially just making more work for yourself down the line. If you get a system balanced at the moment with blocks, block systems and the laser weapon. What happens when you add back missiles and beams? How will you integrate brick ships and systems? I am not trying to suggest that it all needs to be done in one go but I do think if you balance it for a small section of it you are going to find yourself redoing this balancing again down the line when you add the rest of the combat content. In my opinion you are balancing things based on a minority of the content which is just going to cause issues for you. 

![Bricks vs Blocks](https://user-images.githubusercontent.com/25937107/67495898-808e6b80-f673-11e9-95ef-95091c568498.png)
Here's a quick image comparing the basic bricks and blocks in the game. I didn't include pipes or glass because those generally match up or are discussed elsewhere. I circled all the ones that have an equivalent in the other form. As you can see there are only 5 that this covers. With this in mind I think it is fair to say ignoring one or the other really reduces your build options.

**Comment by Battlepixel** [comment]
I totaly agree with gmunga!! Please add current and mass to briggs. 1/64 should do.
I really beg for this! Every time I place a big Block the ships exploding.
I check every day for updates that fix the balancing with small blocks so I can continue to build my fighters. Since each block has 0 heat dissipation and 64 times the mass, it is impossible to continue building or testing.
If the symmetry bug and the values ​​of small blocks are fixed my friends and I can continue to build and try.
 We need this to build cool little fighters like this. 
![20191007183824_1](https://user-images.githubusercontent.com/43222403/67517392-cdd60180-f6a2-11e9-9145-3f998338c98c.jpg)
![20191007183930_1](https://user-images.githubusercontent.com/43222403/67517401-d2021f00-f6a2-11e9-8156-e75f1340a8f8.jpg)

**Comment by tsunamayo** [comment]
Like I said before I cant add heat/hp for brick, the hull system is voxel based.
So I created a new branch in steam with the build before the last.

Branch name is: legacy_system

So that people who are no interested in helping me making progress on gameplay and just want to build brick fighter can continue to do so... =(

**Comment by tsunamayo** [comment]
Check #1500

**Comment by Battlepixel** [comment]
oh man

Maybe it's the language barrier, but it sounds like you're taking it personally.

Nothing I write or wrote was critic and if its sounds like this-> sry googletranslater tries hard but fails maybe/sometimes^^
In my opinion, what sets Skywanderers apart from other titles like SE, SM or Empyrion is the ingenious brick system you have developed. There are no limits to creativity here. Neither in SE, SM nor in any other you can game you can buid small spaceships such as the Freelancer Defender or Eagle, including the interior,  to such a degree of detail. Huge praise for that! Games full of gameplay but less possibillitys to be creative already exist. Of course, the scale of the planetary systems and the look of the game environment is also great, but what makes Skywanderer really stand out are the unlimited possibilities to get creative. There are no ready-made weapons or cockpits like in SE, if you want a Gattling or a pretty cockpit, you can design it yourself.

So in my opinion everything you need to go on alphastate is an working ai and a spawnsystem so people can test and play with there creations. That would guarantee people months of fun and finance your work while you make the gameplay step by step. But without balanced brick system, the possibilities are limited, just like in other already finished games full of gameplay

When I read your post, I realized that your plan or technical options did not fit my imagination and maybe my post was a little bit too panic, because I was hoping so much^^ (sry )-> Whats of cause not your Fehler
But: "So that people who are no interested in helping me making progress on gameplay and just want to build brick fighter can continue to do so... =(" oh man my english isn t best, but nobody wrote that he isnt interested in helping you making progress. All I want to point out is: Please do not neglect the bricksystem when balancing. Your bricksystem is what makes building in skywanderers so interesting. What i can do more than report bugs and try to stay updated.
