### ISSUE TITLE
Only Save in Slot 1

### ISSUE THREAD

**Issue by CyboLP** [tsunamayo/Skywanderers#151]
Hi,

I've started a second Slot for streaming on Twitch, but it doesn't save. After restarting the game, only the first game is available, not the second one... 4 hours of building lost...

**Comment by CyboLP** [comment]
Now it's even not possible, to save slot 1... all my doings are gone... again and again...

**Comment by tsunamayo** [comment]
Okay not sure what is happening. Just a few comments:
1) By design, there is a single world, just several characters. So any change you do to the world will be seen by the other players.
2) Are you putting an identity block and creating a blueprint on any of your ship? 
3) Are you pressing F1 to save the game?
4) Lets try to do a few tests and fix the issue first before spending hours on building and then losing everything.
5) Then I would prefer you to wait to better used to the game in and out before streaming - game is very pre-alpha and not really newcomer friendly as you noticed.

Then could you please provide me with a test case so I can reproduce what you are doing and fix any issues.

**Comment by CyboLP** [comment]
I didn't knee Point 3...
I'll Test it in the Afternoon...
Thanks for the Moment.

**Comment by tsunamayo** [comment]
Sure, keep me posted on how it goes. Regards

**Comment by CyboLP** [comment]
Jep... F1 for saving is awsome... ^^
I'd like an option, which is called "Save and Exit Game" but now, if I know how to save the game, I'll use it now and in the Future!
