### ISSUE TITLE
Suggestion: Streamlined ship speed controls

### ISSUE THREAD

**Issue by PsyCommando** [tsunamayo/Skywanderers#153]
The way changing ship speed also changes the speed controls is really confusing. Not to mention how there are some cryptic conditions to shifting speed modes.

Here are some suggestions:
* Make speed limits toggleable at will, like in freelancer and etc, regardless of starting speed. So you don't need a separate mode and can unify throttle controls to use dedicated throttle keys instead of LMB and RMB. 
* A 6 Direction of Flight flying mode, so you can strafe left and right with your ship outside of MVN mode. 
* Mouse lock to ship pitch/yaw and a mouse lock toggle button, so you can press it when you need to control the character's head to toggle switches and etc inside the cockpit.

**Comment by tsunamayo** [comment]
Thanks, Yes the ship controls are just placeholder for now and will completely redone for now.
I will open a discussion on the forum, but I was going more for the Starwars WW2 control scheme rather than the strafe 6-dof way, if this is making sense.
For sure, throttle wont be RMB and LMB, and we will use a mouse lock to fly ship with mouse.

**Comment by PsyCommando** [comment]
Sounds good then! 
And, what's WW2?

**Comment by tsunamayo** [comment]
This is mostly what we have now. Thanks!
