### ISSUE TITLE
Feedback on Weapon Barrels

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1586]
Following on from 20w04a we have lots of new systems to play with! The barrels overall are a great part of weapon customisation and here we can talk about the values and relationships that might need to be tweaked as part of testing.
Keep in mind that the add-on system is yet to be implemented so some customisation options might be affected by these in the future.

This is my feedback, I encourage you all to join in the discussion below!

- Reload of a laser block should increase the longer you stretch them. A higher damage base gun should fire slower than one that deals less damage unlike currently where all guns fire at the same rate unless you add a Gatling barrel.

- Increase the maximum stretch length of a laser block, but decrease the gains you get per meter. Right now you only have 4 options for laser block length and stats; I don't think that's enough to give a feeling of progression through different sizes of ship. Increasing the max stretch length to around 10m (or the original 16?) would give you a much finer degree of control over the base stats of your weapons and would represent a much bigger difference in gun size between the smallest and largest ships of Skywanderers. To compensate for this the stat gain per meter of laser should be decreased to so that the largest size is only around 3x more powerful than the current max size gun.

- Unify the max length of each barrel. Currently different barrels have different maximum lengths which I feel is confusing and unnecessary. All barrels should have the same stretch limit, and that limit should be larger for the same reasons as the previous point.

- "Cooldown" and "Shots per Second" stats are basically showing the same information. I'd suggest removing the Shots per Second stat and renaming Cooldown to "Reload Time" to prevent confusion.
Some suggestions that have come up on Discord centre around guns having their own heat levels and overheating depending on their stats, if this or something similar is implemented then perhaps Cooldown could have a different function.

- The Gatling barrel is too powerful (even though it looks awesome!) Currently it increases fire rate with no drawbacks at all other than the additional heat/energy per shot. It's also in some ways not powerful enough, as you can get exactly the same result by just using more guns to offset their reload and the heat/energy cost is also the same. I suspect this will be one of the biggest points of discussion so I look forward to reading that, but here's what I think - The Gatling barrel should be removed, and the function of reducing reload times should be given to an add-on. As it stands, the Gatling barrel is easily the best option to put on your gun in almost every situation; the other barrels aren't useful enough in comparison to be be a viable choice in favour of the large increase in DPS given by this barrel in most circumstances. By removing it, you let the other barrels shine in their own way and make it more of an interesting choice which one you use rather than a no brainer to pick the Gatling. 
The add-on proposal is almost self balancing if there's also an add-on for increasing damage. With only limited slots available, you'll have to choose between faster reload times, larger damage or another add-on effect, ideally with diminishing returns and increasing heat values for both.
If it's not removed, it should at least decrease the damage per shot of the gun to compensate the increased fire rate. This would keep the damage per second the same for the gun, but just deal it out in a different way

- Longer barrels should also increase reload by a small margin, especially the range barrel. 

- Longer barrels (especially the Range barrel) should increase accuracy. I haven't seen any differences in accuracy yet so I suspect it isn't a factor, but when it is implemented this would add another stat into the mix to balance your weapon around. A large drop in accuracy could also help balance the Gatling barrel if it is to remain in the game.

- This one is a smaller issue, but I think the connection between the laser base block and barrels is a bit too narrow and weak looking. It's low priority, but this looks especially odd on longer guns
![image](https://user-images.githubusercontent.com/27857711/73549108-de341000-4439-11ea-989c-d7613e6706fe.png)

- The last thing I wanted to bring up was the question of diminishing buff returns and exponential nerfing on large guns. Would this be better than the linear system currently utilised? I'm not sure.

The idea behind a lot of these is to make building your guns a balancing act. You shouldn't in my opinion be able to gain much without sacrificing something else in return. This is to prevent guns that are the best in *every* category and a clear choice over all other configurations.

Looking forward to hearing what you all think! If this is better formatted into separate issues I can split them up for easy ticketing.

**Comment by Doehg** [comment]
I think for the sizing of base gun parts it should be done on volume rather than pure length, as you could get some additional balancing out of making w i d e guns.  Something like increased damage for wider guns and increased reload, accuracy, or range for longer ones.  If not something like this, only trading reload and damage for base length does nothing.  If you make a long, slow firing gun or a short, fast firing gun the dps will be roughly equal, and the smaller base will be the obvious choice.  For adding "stuff" to a gun, there should always be a net benefit, although a longer, more powerful gun will obviously use more heat and energy.  Same with barrels.  If you are adding an attachment, it should be a trade, but there should still be a net benefit.  Probably the best example is the Range barrel.  It should increase range and accuracy, but not decrease much else.  It won't affect damage, and just being able to shoot farther isn't so much an advantage it should be punished beyond the barrel weight and length.  On the other end of the spectrum, the Gatling barrel should increase rate of fire and all the things that come with it, but also significantly decrease accuracy.  The best method of balance is with counters.  A high-damage ship with a gatling gun will lose painfully to a ship with a high power long-range cannon, but a large station or ship will get oof'd by a gatling gun.  Too much downsides and people may not even ever use attachments.

**Comment by tsunamayo** [comment]
Okay intersting discussion here.

- Drawback and trade-off. Yes I didnt took time to add drawback to each barrel,  I plan to nerf them a bit. But @Doehg is right, it still should have a net positive effect. You get only one barrel, so each option should be sexy in itself. Of course barrel would require special items for crafting.
 - Barrel length. I expect people to use max length most of the time. The length only impact the granularity or steps number of the effects, so having only 4 steps seems decent to me. My rational is more a visual thing: in order to not have massively long barrel everywhere I prefer to have something that make more sense visually, aka sniping barrel being overly long, gatling in the middle, ect. The recoil only recoil 1m for various reason, so it would look odds to have a 8m long and only 1m recoil. Yes I loose a bit of consistency but it is not the end of the world. I will make a little stats: max length in the block description (which will be refactored)
 - Cooldown: I agree with that, I will rename it. Yes Shot per Sec is just the inverse...
 - I dont really see the point for increasing the size but having a log return. It seems the same except you get overly long weapons  which is a pain for turrets (and collisions ...), I think for large ship the game will be largely turret based. I mean yes you get more step but I dont see this being an issue. Large ship will have more turrets ;). And more addon ect. For the progression I wanted to add 3 weapons Tier: Tier 1 get one addon row, Tier 2 get 2 rows on two side, Tier 3 gets 3 (or 4...).
 -  Barrel vs Addon: So I wanted to have barrel impact projectile dynamic: rate of fire, speed, range ect. And have addon impact the dmg, give some other effect (power drain on impact, ect). Like how you deliver the payload vs the payload itself. Not sure if it will stay like that though.
 - Accurary: There is none atm, but def I will want to work on that.

But again before doing a more in-depth pass, I want to add more AI and do more combat first -  and address any shortcoming based on real data and feedback.

**Comment by tsunamayo** [comment]
Okay most comment were taken into account. We have accurary, and gatling were nerfed but likely to change again. We will open new discussion based on new elements!
