### ISSUE TITLE
[Suggestion] Link multiple things at once?

### ISSUE THREAD

**Issue by Dwarf-LordPangolin** [tsunamayo/Skywanderers#1606]
I was wondering if it was possible to set the link tool up so that when linking things, there could be some way of linking multiple things while click-dragging the link tool. The reason I'm asking is that I'm almost done with the Whirlwind, but I still need to set its turrets up.

And, uhh ... since it has 32 turrets, this collectively means I'm going to have to link 160 different things to 32 different turret cores, with each click-drag being its own trip.

![20200215223927_1](https://user-images.githubusercontent.com/33041786/74599313-53603180-5045-11ea-91f1-8b629f47acc8.jpg)

Truly, I am a sinner in the hands of an angry god. :sob: 

This is just a quality of life thing, so there's no urgency to it, but if it's possible, some way of linking multiple things without having to go back to the thing you're linking from every time would be handy.

**Comment by tsunamayo** [comment]
Not gonna happens for various reason, I just dont want to add UX and code overhead. I think the issue is that you put all your computer in a central location, instead of putting them locally. I had that when debugging your landing gear also, it was slow to get the going back to your cockpit. I think it would make much sense to put the computer / sequencer close to the mecanism.
Cheers

**Comment by Dwarf-LordPangolin** [comment]
A fair point; I'll start putting logic closer to its systems!
