### ISSUE TITLE
Window Tile Triangle Dragging

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1618]
### Short Description of the issue:
The Window Tile Triangle can only be dragged forwards and backwards on the horizontal axis instead of forward, right, left, and backward
...

### Environment
- Skywanderers version: 20w09a
- Graphics Card: GTX 970

### Additional information:
![20200226150601_1](https://user-images.githubusercontent.com/32974671/75387826-86a68a00-58a9-11ea-8728-71fa8a9e3c67.jpg)

**Comment by tsunamayo** [comment]
Yes it is supposed to be a side windows for your custom canopy build. The back face are more opaque, so it is not really made for free form transparent building.

**Comment by Xerma** [comment]
Having it only drag in 2 directions just doesn't feel right when just about every other brick, minus the obvious few, can drag in all directions. I personally think having this be able to drag in each direction would be a big bonus to the brick palette, especially when there is no block hull wedge.

**Comment by tsunamayo** [comment]
I am not sure to understand, what is that you want to build with? It is not for a canopy / windows right? Or maybe you want a borderless canopy? 
Because there is not mini cube transparent, no tetra, no hepta ect. This brick was made to so you can close your canopy on the side.
Cheers

**Comment by ProPeach** [comment]
![image](https://user-images.githubusercontent.com/27857711/76435178-94323880-63ae-11ea-8b25-3ad50007f41b.png)
If this is for closing the side of a canopy, can it be thinner to match the thickness of the metal part? I didn't realize that was the bricks intended function because it looks so out of place from the front. From the side it looks good though
![image](https://user-images.githubusercontent.com/27857711/76435330-c774c780-63ae-11ea-8b40-da9eb0d9c476.png)

**Comment by tsunamayo** [comment]
Hum I see, the problem being it would no longer be symmetrical, with a lot of issue coming from that.
It guess it would be better to make the frame larger ... Thanks

**Comment by ProPeach** [comment]
Other games, namely Space Engineers, solve this problem by having a different shape for left and right, but if I remember correctly the issues come from the mirror system both being able to handle that yet.

Widening the frame to fit the wedge glass would remove a lot of the benefit from having brick glass, making it difficult to see out of. Would it be possible to slim the wedge down to half a brick thick, and then enable it to be placed in half a brick increments like stickers? That way it would take up half the width it does currently while not causing issues for mirroring. Ideally it would be a quarter brick thick with quarter brick placement, but I recognise that might not be possible.

**Comment by tsunamayo** [comment]
Yes it makes a lot of sense to make it smaller and add a smaller brick increment, it will be the easiest solution I think.
For the smaller size unfortunately I cant really, as the stretch tech is a bit special for these shape and wouldnt work with a 0.25cm. I know it would be more logical but lets face it you are not gonna build canopy this thin so no big deal. 
If you really need one then a simple wedge or tetra would do the work I guess? I might add them instead.

**Comment by ProPeach** [comment]
Awesome, glad we solved that case.

It's not just that a one brick sized canopy would be useful (Which it would), it's also all the shapes you can create when you stretch that. You can achieve 0.25m x 1m, or 0.25m x 0.5m shapes etc rather than having to start out with one dimension at 0.5m. These are the kind of use cases I was thinking of when I suggested it. Players absolutely would use that added functionality, and not only for thin canopies - when you combine that shape with the others it can be used as a bevel, part of a curve, an angled side to a canopy, a thin visor like window or part of a ships interior.

**Comment by tsunamayo** [comment]
Okay I have made the new side triangle thinner, and made the frame thicker to match their size. I will make trans only (no frame) version also, for super small or complex canopy. Thanks!
