### ISSUE TITLE
20w12a: Block engines no longer contribute to angular velocity

### ISSUE THREAD

**Issue by Lsutehall** [tsunamayo/Skywanderers#1657]
### Short Description of the issue:

It looks like block engines no longer contribute to angular or lateral velocity when placed sideways.

### Steps to reproduce the issue:

- Make a ship with only block engines, including the sideways ones
![unknown1](https://user-images.githubusercontent.com/40872394/76895196-7588e180-6887-11ea-8aee-a79395f3ddaf.png)

- Check spaceship core: angular velocity = 0
![unknown](https://user-images.githubusercontent.com/40872394/76895219-7de11c80-6887-11ea-8f6d-287db3fe58ee.png)

- Place brick thruster sideways

![20200317174412_1](https://user-images.githubusercontent.com/40872394/76895263-90f3ec80-6887-11ea-8d9d-c74e54e1a5cb.jpg)

- Check ship core again, now shows angular velocity:

![20200317174426_1](https://user-images.githubusercontent.com/40872394/76895293-9ea97200-6887-11ea-95bc-20b15ba5ef1b.jpg)

### Environment
- Skywanderers version: 20w12a
- Graphics Card: GTX1060

### Additional information:
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/4345487/output_log.txt)

**Comment by tsunamayo** [comment]
Yes it is not a bug, I forgot to mention that in my release note, now the big thruster can only give forward and lightcruise thrust. 
The description of the block is updated to reflect this.
Lets see what other tester think about this.

**Comment by ProPeach** [comment]
What were your reasons behind this? Personally I don't see a problem with them working for angular thrust, it gives you more options on how you use your heat/energy given their different benefits

**Comment by tsunamayo** [comment]
The meta decision behind this was to naturally get fast maneuvrable small ship and slow large one.
Otherwise with the older system there is nothing that prevent you to get a super maneuvrable 300m bememoth. Now with that system you must use small thrusters, and they are more heat hungry, which will be harder for large ship. I dont know if I am clear ;)...
Cheers

**Comment by ProPeach** [comment]
That makes sense, because larger ships don't get the same surface area heat dissipation buff as smaller ships they wont be able to place as many heat hungry small thrusters.

I kinda assumed you were already penalizing large ships in the calculation for agility, where the larger a ships mass the harder it is to raise it's agility level with diminishing returns. That is to be expected as we all know bigger ships are generally more sluggish. Forcing the player to use the brick thrusters on large ships feels odd as you'd expect large ships to have larger maneuvering thrusters, but it does eliminate any possible confusion about the uses of each thruster type.

On a somewhat related note, do you plan on introducing mechanic to encourage players to place thrusters on the outside of the ship rather than the inside? Something like thrusters saying blocks, or increasing hest by a large factor if they're blocked.

**Comment by tsunamayo** [comment]
Oh yes I want to forbid that, otherwise it push player to close their thruster. 
Again I dont really care if some people want to enclose their thruster, the problem is that the most optimum way of playing is enclosing your thruster, which might frustrate some player caring about efficiency and look altogether.

**Comment by ProPeach** [comment]
I agree, if players could enclose their thrusters it would become very common, especially for side thrusters I think as not everyone likes having to use them and for combat ships.

The only problem I see is it will be hard to balance this around aesthetics, as most builds I've seen like to build a border around the thruster for a different thruster shape, or create a grill over it with bricks.  Perhaps if only ~60% of a thruster needed to be open for it to function correctly that would be the best of both worlds

**Comment by tsunamayo** [comment]
Yes, it is gonna be tricky to get it right... I will try to allow for a border. I will tell you once it is live.
