### ISSUE TITLE
Mirror Axis Remains

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#1678]
### Short Description of the issue:
It seems that if a ship has mirroring activated, if you despawn the entity using the F5 drone then the mirror plane stays there until the game is restarted.
...

### Environment
- Skywanderers version: 20w13b
- Graphics Card: GTX 970

### Additional information:
![20200401192300_1](https://user-images.githubusercontent.com/32974671/78198637-c8999180-744e-11ea-96c9-790868642458.jpg)

**Comment by Aiwii** [comment]
The mirror axis also follows you if you teleport to a different ship while keeping mirror on

**Comment by tsunamayo** [comment]
I see. By the way do you think the new rendering is okay? I try to make it less intrusive but I think it was important that always have a visual clue of it being there. Also I hope you like the new toggle.

**Comment by ProPeach** [comment]
The toggle is an excellent feature, thanks so much for that. I also like the minimalist look of the mirror plane, it makes it much harder to forget to enable mirror and then realise too late and have to rebuild a section of your ship.
I suggest that the mirror outline should disappear when you pilot the ship though if possible, just as a quality of life thing.

Another semi-bug, the mirror plane jumps around erratically if you move too fast while looking at it. The same thing happens if you move the ship too fast with it enabled

**Comment by tsunamayo** [comment]
The various issues are all fixed:
 - Still show when delete
 - Popup when moving
- Show when flying.

Thanks!
