### ISSUE TITLE
[Suggestion] Grav gen placement

### ISSUE THREAD

**Issue by ZachZent** [tsunamayo/Skywanderers#1684]
To cut to the chase, I would like to recommend that the grav gen block be able to be placed on the brick grid similar to the seat. Right now being that it is on the block grid, you have to place it on top of a block and on the floor given that you need the gravity to face down. This just makes it an odd obstacle to stub your toe on. It isn't a problem with larger ships where you have the space to hide it out of toe stubbing range, but in smaller ships which can't sacrifice the space it can be a problem. Being able to move it on the brick grid would allow us to embed it in the floor of your ship.

Another option is some sort way to change the gravity's direction in the UI rather then have it based on placement direction. That way you would be able to place it on walls or ceilings out of toe stubbing range.
https://cdn.discordapp.com/attachments/406664114249793536/695186798770389053/unknown.png

**Comment by tsunamayo** [comment]
Oh yes I though both were possible, I will fix this.

**Comment by tsunamayo** [comment]
This will be improved for next update. Changed item are:
- you can change the direction in the UI
- the default direction, which is made so that you put the block on a wall. 
- There is preview arrow
- Power and heat requirement is constant (I think that will be simpler to deal with)
- You can place it like a small brick
- Seat also can now be placed like a smaller brick.

Cheers

**Comment by ProPeach** [comment]
Great news about the seat, super cool grav gen changes too!
