### ISSUE TITLE
wrong mass-calculation

### ISSUE THREAD

**Issue by Arschpollo13** [tsunamayo/Skywanderers#1692]
1)The mass calculation of small bricks is too large and this will make small fighters too heavy.

2)The second problem is (as can be seen in the bottom two pictures) the mass calculation is not correct for the window parts or other blocks that are constructed in this way, which makes small ships extremely heavy.
![Screenshot (9)_LI](https://user-images.githubusercontent.com/63169168/78461552-66e55b80-76ca-11ea-8631-e1ffd3b5e02d.jpg)

For comparison to the windows I have the same ship with a normal hull and this would be even lighter.
![Screenshot (12)_LI](https://user-images.githubusercontent.com/63169168/78461935-85992180-76cd-11ea-8bc7-dfc5323b6ed7.jpg)

**Comment by Battlepixel** [comment]
An example:
These are the two reasons why a normally 22 ton Hornet, the inside of which consists only of drive blocks and the necessary generators and is otherwise empty, weighs 170 t ingame and is not faster than 180 km / h,

![image](https://user-images.githubusercontent.com/43222403/78815587-c3998c80-79d0-11ea-9f1a-c50030858349.png)
mass: 170t

![image](https://user-images.githubusercontent.com/43222403/78815700-e75cd280-79d0-11ea-8fe6-d4a8d5924595.png)
highest ingame speed after 20s full thrust


![Skywanderers_2020_04_08_19_42_57_682](https://user-images.githubusercontent.com/43222403/78815913-36a30300-79d1-11ea-979b-d24018a6505d.jpg)
values that the ship core shows (speed ist not shown right, its twice the real value, mass is only different berause of the ssecond shipcoreblock)

**Comment by tsunamayo** [comment]
Okay I did a pass on this, ship will be now lighter and windows weight scale more logicaly.
Will most likely a bunch of other pass after having a look at other ship. Will be in 20w14b.
Thanks!
