### ISSUE TITLE
[Bug] Weapon spread is only in one plane

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#1704]
### Short Description of the issue:
Following the addition of weapon accuracy to the game, it looks like projectiles only deviate in one plane (the vertical plane if the add-on slots on the gun are facing upwards) rather than in many planes resulting in a circular spread pattern

A max length gatling laser (spread 6.25 degrees) 100m away from a target.
![image](https://user-images.githubusercontent.com/27857711/78916264-1df42500-7a85-11ea-8cb0-2b646496e36d.png)

### Steps to reproduce the issue:
Setup a gatling gun with Charge modules to fire more rounds and a target, then fire many shots. You can see that they only deviate in one plane.

### Environment
- Skywanderers version: 20w15a
- Graphics Card: RX 580

On a side note, the values for the degree of spread are much too high at the moment. At 100m, a max length Gatling barrel has a spread of 22m total while a max length Range barrel has a spread of 6m. These would be better for a range of around 1km, rather than 100m. I'd suggest dividing all current spread values by at least 10 as a starting point to make them more accurate, it's difficult to hit targets at even very close ranges currently.

**Comment by tsunamayo** [comment]
Issue fixed for 20w15b. I adjusted the base spread to 2 instead of 5, but I prefer to keep it too high for now and get more mileage of the combat. Gatling should stay very much a close range weapon, being accurate at 1km away seems already very far to me - I want to make longer sniping barrel attractive also.
We will tweak that for sure. Cheers
