### ISSUE TITLE
[Balance] Small brick laser beam is far stronger than large block beam

### ISSUE THREAD

**Issue by Starwhip** [tsunamayo/Skywanderers#1774]
[Small array vs large beam comparison](https://imgur.com/a/npdesUd)

16 fully stretched brick size laser beams do a total damage per second 4 times greater than one fully stretched large block beam, and take up one quarter of the space (Making them 16 times more powerful per cubic meter).

I recorded a video of how this could be used in practice here, with the stats of 1 of the small beams vs one of the large beams. [https://youtu.be/YylKX5FB1Tk](https://youtu.be/YylKX5FB1Tk)

Small beams should at least have some drawback to compensate for their power. Stat wise, currently they do ~4.03x more damage per cubic meter, but drain 4x more energy and make 4x more heat, so they are technically better than the large block, but not by much. Their energy consumption and heat generation could be upped dramatically to compensate for how much punch they pack, or they could just be scaled back a bit. Making them 2x more powerful per cubic meter than the large beam would mean that a full size large beam would be twice as damaging as a full size small beam array, while being 4x larger.

**Comment by tsunamayo** [comment]
There should be an issue, they should be much more heat inefficient compared to the large one.
The idea with small brick is that they are powerful volume wise compared to the large one (otherwise figther would be ridiculously under powered compared to even small-medium block ship, and people like fighter) , but they are heat inefficient so that larger build would need to rely on larger block. 
Space is not an issue for larger build, heat is, whereas for small fighter space is an issue and they have some heat freedom because of the surface heat mechanism.
