### ISSUE TITLE
[BUG] Major desync for host when connected party interacts with anything.

### ISSUE THREAD

**Issue by Midge57** [tsunamayo/Skywanderers#215]
Using EVOLVE, as I cannot port-forward. Connecting party joins fine, can see each other moving, he could place blocks etc- But pressing any kind of button or using a joystick etc would cause him to freeze in place on my screen, and I could no longer interact with anything. His game continued fine, but I would be frozen in place on his screen too. This would be fixed by him leaving and re-joining, and upon him leaving my game would catch up and everything I interacted with would do the animations.

**Comment by JohnMasonSK** [comment]
I Have the same bug, it seem to occurs after interact a number of times with logic (button,gates ...).

**Comment by tsunamayo** [comment]
I fixed a bug with link assigment on torus, not sure if it was your test case.

When there is a freeze like that, and game start to be broken, it means that there is error being spit out in the log. If you could send me your output_log file inside the game Steam folder it would be of a great help to me. When that happen, no need to stay in the game for too long - game is broken, you can exit quickly in order to keep log smaller. 

Please re-open the case if the issue was not fixed - starting from the next build. Cheers
