### ISSUE TITLE
[SUGGESTION] Collapsable/Deformable blocks

### ISSUE THREAD

**Issue by Nexusdog** [tsunamayo/Skywanderers#216]
See: Carpenters blocks mod for Minecraft for basic idea

Request manipulation of block shape for greater detailing, etc.

**Comment by tsunamayo** [comment]
Yes I was thinking of doing that to fight the exponential number of blocks needed because of 1/2 1/4 length... A block where you can shift face, vertex and edge, like in maya ;-). But I need more time to think about the integration - as there will be quite a few challenges. But I like the idea. Could be better for performance also ;)

**Comment by Nexusdog** [comment]
Merci! Merci! Merci!
