### ISSUE TITLE
non logical placement of blocks ect

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#253]
When placing blocks atm wit say a sloped edge, you currently drag the block in such a way that the slope/ smallest edge points to the mouse, it would be more consistent with other building games if the biggest edge was towards the mouse.

When placing logic, apart from being hard to tell witch direction the 2x2 boards will place on, it seems that the way it is place is you click where you  want the output to be and drag in a direction you want the input to be (this is with a 1x2 board).
It would make more sense if is this was reversed so you  click where you  want the input to be then drag in the direction where you want the output as when you are making a circuit, very rarely do you start at the end and work in reverse.

The mass delete function (hold shift and click and drag) and the mass place function (hold place block then tap alt) should both use the same key and act in the same way, the amount of time ive held alt then gone to place a row and it hasn't done anything or gone to delete a heap of blocks and started to remove a block then tapped shift. My suggestion is they both shift as their "modifier" key and you have to hold shift prior to attempting the action, you would still tap it again to cycle through the _line, panel and cube_ and of course this modifier key should be rebound .

Also on the subject of mass placement the way it works currently where you can only expand parallel to the block you were targeting with the origin of the line is very annoying, adding the last axis would make building some things alot easier.

**Comment by tsunamayo** [comment]
For 1st) it is like that because you always want the slope to face you, and it is much easier to hit the closest quadrant of the surface that is near to you (because it is bigger).

2) for two I could change it, the problem is that it will destroy the lick assignment for all ship already built... 

3) This will be refactored soon. I wont make mass placement 3d, but I will give you the ability to rotate the plane. CTRL push will be removed altogether. 

Thanks
