### ISSUE TITLE
Game is crashing on startup

### ISSUE THREAD

**Issue by darthdaddy87** [tsunamayo/Skywanderers#311]
I have it on 640 x 1080 windowed
[2017-10-30_173916.zip](https://github.com/tsunamayo/Skywanderers/files/1429200/2017-10-30_173916.zip)

**Comment by tsunamayo** [comment]
Hello, sorry to hear that.
Could you please give me your computer specs, and also make sure that your GFX driver are up to date? You seems to have a very low-end GFX card. Thanks

**Comment by CaptainCJH** [comment]
Since update today games crashes on startup.
Dell Q6600 2.4ghz Pentium Quad Core 16 MB DDR2 RAM
NVidia Geforce GT 730 1GB VRAM running V388.00 drivers
Windows 10 64bit
Log files:
[2017-10-31_154402.zip](https://github.com/tsunamayo/Skywanderers/files/1432299/2017-10-31_154402.zip)
[error.log](https://github.com/tsunamayo/Skywanderers/files/1432293/error.log)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1432294/output_log.txt)

**Comment by tsunamayo** [comment]
GFX under spec. Thanks
