### ISSUE TITLE
Custom colors do not work properly on some system bricks (17w44a)

### ISSUE THREAD

**Issue by Segdis** [tsunamayo/Skywanderers#349]
Some system bricks (such as screens, projectors, and buttons/switches) will use the default value for a custom color in some parts of their appearance, while using the player-set value for others. In the attached picture, all affected bricks were colored with custom color 1 in the hotbar.
![custom color bug](https://user-images.githubusercontent.com/33088776/32351753-e0798e60-bff4-11e7-9c5a-702a65c4ab61.jpg)

**Comment by tsunamayo** [comment]
Thanks, yes indeed this feature is still wip. I will fix it! Thanks

**Comment by Napther** [comment]
I actually dont think of this particular bug as a bug than a feature.
Dual-colour (while limited to 8 starting colours) on a screen is pretty neat. Just gotta plan for it... Unless it instead follows Pipe colouring scheme where first click does the Nodes, the next colours the nodes again the new colour, but the old colour is the new pipe colour. Etc, etc.

**Comment by tsunamayo** [comment]
Hum the thing is I will give you completely editable screen (ie they will be all editable like the Text Screen), instead of the current linkable one.
In text screen you can pick any color you want for the text. 
I will add more feature to the text screen, like the ability to display to output of any system. But I wont work on that before a while though. Cheers

**Comment by tsunamayo** [comment]
Issue deprecated as there is no longer custom colors. Thanks
