### ISSUE TITLE
[Experimental] Bricks not placing on flat panel

### ISSUE THREAD

**Issue by Xerma** [tsunamayo/Skywanderers#354]
I saw this issue popped up a few days ago for some people and the issue was closed/fixed. I'm having the exact same issue in the most recent experimental build.  It seems to occur after breaking a brick on a flat panel and it won't let me place a brick anywhere else unless I restart my game entirely. 
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1440332/output_log.txt)

**Comment by CyaNox** [comment]
Current Experimental build is still the same as the stable branch and has not been updated since 17w44a.

This issue is most likely fixed in the next release after 17w44a as per #314.

For the time being try using the 2x4 flat panel instead.

If this is a different issue altogether and still happens in the new build please don't refrain from commenting here ;)
