### ISSUE TITLE
Bricks have missing studs on the face that you are placing down

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#359]
While building furiously with the lovely bricks I found myself quite often missing studs on the already placed bricks I had. After further investigation I found that the studs are always missing on the side that was placed down.

The video below shows where I am missing the studs and how to find them:

https://youtu.be/YjSBl2gKqlI

This happens to just about any brick as far as I've seen.

**Comment by Napther** [comment]
THis is a limitation of the Brick System IIRC. Bricks =/= Voxels, However the game really hates when you place a Stud grid on the base of Bricks that do not have a stud due to placement. It will act as though it is placed, but nothing will. Pressing Undo will then delete the brick you tried to place onto...

**Comment by Segdis** [comment]
This issue was posted before in #103. From the response given, it sounds like it is a result of how the brick system works.

**Comment by Mellcor** [comment]
its still very annoying to work with, having to place "scafolding" just to get a useable stud

**Comment by CyaNox** [comment]
As much as I'd like to accept an answer of "This is a limitation of the system" it still does not feel right. I've encountered situations where I accidentally broke the wrong stud and had to build up a bunch of scaffolding just to fix my tiny mistake. If the studs were there I would have been able to fix it immediately instead of having to work around a "limitation".

**Comment by Mellcor** [comment]
as nox pointed out the current system is something that should be pretty high on the todo list as i should hope this 'limitation' is not in the released product, nothing like having new playing trying to work out why they can put a block somewhere and then finding out they need to use some unintuitive workaround by means of placeing scafold bricks 
especially after tsuna whent to tall the work of making it so you dont need to scafold with full size cubes

**Comment by tsunamayo** [comment]
This is actually a very fundamental issue, and just the tip of the iceberg.

Yes I get it is painful for you guys - I have experienced that also. The stud you are trying to build on is actually already occupied by the bottom of the brick you want to build on... There is no stud on the bottom of brick, bricks are like lego (there is no stud on the bottom of lego)
In the code there can only be a single brick on a stud. 

Overall it seems that people are getting confused by the nature of bricks, they expect them to be just smaller voxel. This is one my biggest problem looking forward - I was not expecting that, so it might require some heavy change in the game - or having me to find a way to explain that to the player in a way that feel right and not arbitrary...

I will see what I can do to work around that - I have several options but they are all messy in a different way.

One of the "radical" approach could be to delete all children brick (brick build on the studs of the parent brick you are deleting)! It would prevent the use of scaffolding brick but would seems more tangible for the player...

One of the other "radical" approach would be to transform brick into mini voxel. But a lot of half width or offset brick would have to disappear. This would seriously hinder creative possibility when it comes to making small details for mechs or weapons (especially when I will add back handheld), which was the reason I put them in the game in the first place. And that would be a heavy change in code.

If those kind of dilemna are interesting you can suggest things!

**Comment by tsunamayo** [comment]
@Napther actually it is because flat stud are a big hack to work... I will need to prevent them to be place in case like this. This is related to one your existing case #309 . 
@Mellcor  Actually when you think of this issue it means that scaffolding brick are not working well. It means that often you have to create complex and painful scaffolding contraption to do what you want...

**Comment by Mellcor** [comment]
exactly, i can understand scafolding if u want to get a block info a position where it clipps with another block but when u need to scafold to place a block next to another thats when i beleive its an issue

**Comment by Rizzo911** [comment]
I can understand the crazy overlapping of these bricks, but it seems that the issue is not just in the case mentioned. I've seen this happen when just stacking bricks of the same exact size (say the cube). You remove a brick and the underlying stud also gets removed making it difficult to place down a replacement and then you have to do some crazy delete and build pattern to get a working stud back. Are we sure this last part is intended?

**Comment by AfterRebelion** [comment]
Studs are no longer a thing, so this is no longer an issue in recent versions (19w23b)

**Comment by tsunamayo** [comment]
Yes, it was still an issue even after the removal of stud, but I did a major brick refactor a few weeks back that solve that design issue among other things. Cheers

**Comment by AfterRebelion** [comment]
Oh, never had this issue since the removal of stud, and the new brick seemed so different that I was sure this no longer applied, but good to know this is fixed.
