### ISSUE TITLE
Consortium of Missing Blocks: Initial block assessment

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#384]
<div align="center">
<img src="https://user-images.githubusercontent.com/33279412/32422947-c2632448-c2a3-11e7-91fe-5759dc8a3a12.png"  align="top" /><img src="http://cyanox.nl/text/?f=uni05_1&s=36&t=Consortium%20of\nMissing%20Blocks&c=0b1631&a=5" />
</div>

---

The Consortium Of Missing Blocks has been established by the five major factions; The Petcha, Senrai Mining Corporation, House Imperitus, The Coalition and House Elgari.

Our goal is to reduce and or eliminate any missing blocks, shapes, textures and anything else related to missing blocks or bricks.

Our initial assessment is about the Hull Blocks and we've documented in detail many of the missing blocks:

![2017-11-04-20-24-02](https://user-images.githubusercontent.com/211381/32423227-69eadcb4-c2a5-11e7-9bc2-e9436693d3c3.png)

Here is the blueprint of the above construction: 

[COMB Missing Hull Blocks.zip](https://github.com/tsunamayo/Skywanderers/files/1444784/COMB.Missing.Hull.Blocks.zip)

Because of the large amount of missing blocks we've established that there may be a solution that could eliminate a great quantity of these missing blocks. We've found that the shapes of blocks should be decoupled from their texture making it so that one can paint a texture onto any block. This will make it so that the number of unique blocks in the various menus is drastically reduced but does introduce another different tool; The texture tool. This new texture tool would go along well next to the color and linking tools.

One alternate universe that already has something like this is Empyrion . In Empyrion you do still have different block materials like Wood, Steel, Hardened Steel, etc. which all have different properties but all can be textured and painted with all available patterns. On top of that it also allows for each individual side of a block to be textured or colored differently. Below a screenshot of the Texture tool selections:

![empyrion_textures](https://user-images.githubusercontent.com/211381/32423351-23f23d64-c2a6-11e7-8563-fe1296c19006.jpg)

We the Consortium of Missing Blocks are very aware that these changes may impact a very large amount of existing structures and craft but we do feel that a solution to simplify future assessments of missing blocks would be highly advantageous.

Signed The Petcha:
![sw_signatures petcha 128](https://user-images.githubusercontent.com/211381/32423280-cceed356-c2a5-11e7-940d-d51f05cfc52c.png)

Signed Senrai Mining Corporation:
![sw_signatures smc 128](https://user-images.githubusercontent.com/211381/32423275-ca3aa34c-c2a5-11e7-88d1-cfbd9a216d50.png)

Signed House Imperitus:
![sw_signatures imperitus 128](https://user-images.githubusercontent.com/211381/32423272-c1cdd6fc-c2a5-11e7-9fc7-0a01f3b6c738.png)

Signed The Coalition:
![sw_signatures coalition 128](https://user-images.githubusercontent.com/211381/32423258-a4126eb6-c2a5-11e7-87dc-e7b2afe37769.png)

Signed House Elgari:
![sw_signatures elgari 128](https://user-images.githubusercontent.com/211381/32423270-bbaf9dd2-c2a5-11e7-9d1f-e1ccbb4e7fa4.png)

---

I hope this is not too confusing and that my desire to have some fun with the lore of Skywanderers isn't stepping on anyone toes. Either way all the assets that I made for this feature request are available here:

[sw_comb_assets.zip](https://github.com/tsunamayo/Skywanderers/files/1444792/sw_comb_assets.zip)

They are made using [Inkscape](https://inkscape.org/) and I've assigned all copyrights to TsunamayoCorp.

**Comment by tsunamayo** [comment]
Haha very nice presentation for the feature request I enjoyed reading it ;-)!!
Okay I totally see the problem you want to solve, and I totally agree it needs to be addressed.
The Texture tool have pop-up several time and I also myself thinked about it. I dont like it because of a few reasons:
 a) It is immersion breaking. It looks too much like an editing software, in real life you dont "paint" wood into concrete or so on. 
 b) It doesnt map well for survival: each hull will have crafting requirement and different properties, which doesnt fit well with the tool.
 c) It doesnt map well at all in the code, of course I could make it work but I would prefer not.
 d) it wont prevent people to come up every day saying how I need this shape to combine with this one ect

The way I intended to solve that problem is to only keep the basic Hull Five familly (block wedge tetra hepta corner), and have a "magic block". You would be able to drag and drop each vertex / edge / face of this block to match any shape you want. 
Note that this solution is just slighty better in my eyes because it still look like an editing software (which I am religiously against) and will still take time to dev, but on the otherhand I get rid of all those endless block shape,  people can make all the shape they can dream of, and it will be good for fps as it will save a significant amount of tri. 
Ressources wise lets say you want to overlap with 4 voxels with a single magic block, it would still consume 4 magic blocks from your inventory.

If I somehow manage to make it works I could then try doing other kind of magic block for rounded surface and complex canopy, each with different way of editing them.

Tell me what you think of that.
Cheers

**Comment by CyaNox** [comment]
<div align="center">
<img src="https://user-images.githubusercontent.com/33279412/32422947-c2632448-c2a3-11e7-91fe-5759dc8a3a12.png"  align="top" /><img src="http://cyanox.nl/text/?f=uni05_1&s=36&t=Consortium%20of\nMissing%20Blocks&c=0b1631&a=5" />
</div>

---

The Consortium of Missing Blocks has determined the the proposed solution is acceptable for solving this initial assessment and is looking forward to its implementation.

Signed The Petcha:
![sw_signatures petcha 128](https://user-images.githubusercontent.com/211381/32423280-cceed356-c2a5-11e7-940d-d51f05cfc52c.png)

Signed Senrai Mining Corporation:
![sw_signatures smc 128](https://user-images.githubusercontent.com/211381/32423275-ca3aa34c-c2a5-11e7-88d1-cfbd9a216d50.png)

Signed House Imperitus:
![sw_signatures imperitus 128](https://user-images.githubusercontent.com/211381/32423272-c1cdd6fc-c2a5-11e7-9fc7-0a01f3b6c738.png)

Signed The Coalition:
![sw_signatures coalition 128](https://user-images.githubusercontent.com/211381/32423258-a4126eb6-c2a5-11e7-87dc-e7b2afe37769.png)

Signed House Elgari:
![sw_signatures elgari 128](https://user-images.githubusercontent.com/211381/32423270-bbaf9dd2-c2a5-11e7-9d1f-e1ccbb4e7fa4.png)

**Comment by tsunamayo** [comment]
It is gonna take a bit of time before I start working on this though ... =(

**Comment by ColdSpiral** [comment]
On the topic of missing blocks - can we also get a square "Canopy Sided" in the colourable/borderless canopy style, please?

**Comment by AfterRebelion** [comment]
Since freeform is already avaliable, this issue is mostly fixed in recent versions (19w23b)
But there are still some block that suffer from this, like the wood plank block, that only has the full block variant.
