### ISSUE TITLE
[SUGGESTION] don't remove all the repeater logic...

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#407]
a while ago it was said that you plan to remove the quad and dual output logic gates and instead make it so you can link and output to as many inputs as you would like, however i think it would be a good idea to have a version of the output gates except minimized (would only have one input and one output)

the reason for this being say you want to join lots of systems together, but they might be other other sides of your build, this would serve as a sort of checkpoint for ease of access to the inputs of multiple systems without having to go to the actual systems or to the logic prior to the systems

**Comment by tsunamayo** [comment]
Okay when I do this update I will add such a repeater block indeed. Thanks

**Comment by CyaNox** [comment]
I've actually found a use for the dual link gate that may not have been entirely anticipated:

![2017-11-20-18-30-37](https://user-images.githubusercontent.com/211381/33032215-d60eeb3e-ce20-11e7-9413-3340263e6fb0.png)

This creates a rapid pulse on a single button press since the dual link creates two separate packets which both trigger the button and very quick succession.

**Comment by AfterRebelion** [comment]
You can use a OR gate to make this effect, so this issue is no longer valid in recent versions (19w23b)
