### ISSUE TITLE
(Suggestion) Add output time to buttons 

### ISSUE THREAD

**Issue by EthanWJohnson** [tsunamayo/Skywanderers#418]
For logic circuits and buttons, I'd like to suggest adding an output time to the button that we can configure like we can with the delay gate. So a button could be pushed, output on (1) for .2 seconds and then turn off again, or output on (1) for 2 seconds at a time.

I ask because, due to the delay gates some looping code can be a bit unstable. I created a T Flip-Flop circuit, and unless I time the switch exactly right the flip flop will either fail to switch output sides or will enter an unstable state constantly toggling on and off for both sides.

**Comment by tsunamayo** [comment]
Hi, okay I am not sure to understand 100% your request, maybe the best is for you to send me your blueprint with the mecanism you want to build, and see what is wrong with the engine. Thanks!

**Comment by talrey** [comment]
Ethan, Skywanderers works with a packet-based system rather than a current-based approach like actual electronics. When you push a button, it emits a one-time packet of data with a value of '1'. The data in a packet can be any value between and including 0 and 1. This may be where your confusion is coming from.

Incidentally, a TFF is _super simple_ with this game. If you wire a switch to something, the switch will (obviously) output a 0 or a 1 depending on its state. What's not obvious is that you can wire things _into_ a switch, and any received packet will cause the switch to toggle!

**Comment by EthanWJohnson** [comment]
Interesting, so we'll have to make usual logic circuits without relying on pulse lengths--i suspected it worked that way, but wasn't quite sure.

Disregard the above suggestion then, i'll keep yelling at the logic system and see if there's other lacking areas.
