### ISSUE TITLE
Sliding Extension inconsistent extension distance

### ISSUE THREAD

**Issue by CyaNox** [tsunamayo/Skywanderers#419]
While playing around with the sliding brick blocks I found it to be inconsistent in the distance they traverse when you activate them.

In the image below we have sliding bricks with zero, one and two extension bricks.
![2017-11-10-00-20-20](https://user-images.githubusercontent.com/211381/32634677-099939e0-c5ad-11e7-9dbc-e35630b9e48e.png)

As you can see the inconsistency lies with the first extension which only extends the sliding brick by 0.5m instead of the full 1m as you would expect especially if you consider that a second extension brick ___does___ extend it by 1m.

The purple coloring designates what I expected.

Below a blueprint with a simple test case with both variations of the sliding brick:

[Bug Sliding Brick Extension Incorrect.zip](https://github.com/tsunamayo/Skywanderers/files/1459519/Bug.Sliding.Brick.Extension.Incorrect.zip)

**Comment by tsunamayo** [comment]
Yes, the exception is when you have no extension, instead of moving of 0, it move 0.5m to the right or the left. It might not be logical indeed, but it was to get at least some movement with the basic one. I will completely redo the rail system at one point btw, so I will leave it like that for now. Thanks!
