### ISSUE TITLE
Powergrid

### ISSUE THREAD

**Issue by Harlekin13** [tsunamayo/Skywanderers#499]
As there will be the time when energy generation and consumption will be implemented, i assume there will be some kind of powergrid (I'll call it that way for now).

What i mean: an energy core will be able to be turned on/off, there will be wires (like with logic components now) that connect energy cores with energy consuming components (or components that one wants to be able to unpower), that deliver not a pulse of some value but a state (on: I'd say a value of 1 continously or off: no signal at all). I think there should be a additional component to only unpower some components instead of all connected to an energy core, which then needs to be connected to it.

Why do i propose this?
Because I'd like to unpower doors to lock them or deactivate elevators, love that energy rerouting from the engine to the weapons/shields or otherwise and foremost i want to ready the weapons before accidently firing them. And i think it could be quite interesting for space combat too, as one could try to destroy the enemies energy cores to disable their weapons and engines.

Perhaps one could implement a new weapon class, ion weapons, which drain energy output of the ship they hit, but don't do much damage, perhaps even none. For that all to work it could be necessarry to change the ship, mech and hover cores to generate energy too, perhaps halve an energy core? That way a big ship would profit from a few mechs to defend it when unpowered and a few hovercars to fastly transport personal to these mechs in the same case. that way players would have to look into building mechs and hovercars even after they took off to space.

**Comment by tsunamayo** [comment]
Thanks for the suggestion, I see you are also participating to the official suggestion thread on energy. https://www.skywanderersgame.com/forum/viewtopic.php?f=11&t=286&p=1757#p1757
For the door locking I think it should be done in another way, via and ID or key system for example. For the weapon as discussed there is way of doing that already.
Yes I want that system to give depth to the combat mecanics, it could be cool to make boarding / not destructive ship for example. 
Cheers

**Comment by Harlekin13** [comment]
The biggest difference in the lock techniques would be, an unpowered door does not open if an intruder got a key somehow... ^_^ Such a thing could make a security station on the bridge a valuable asset. "They seem to have a key!"-"Lock the blastdoor in front of them and the one behind them and then unpower these blastdoors, and send some security bots there for when we open them again."

**Comment by Napther** [comment]
Instead of Ion call it EM(P) or Energy Disruptors. As ions are high-energy particles that could just be weaponized to strip away powered shielding and light/unprotected systems.

I am, however, against the idea that EVERYTHING should be powered as that would add massive tedium to the game. Already there arent any basic toggle-doors, so each have to be built on a unique basis. THe extra chore of linking it up to a system is something I'd rather avoid.

However. The inverse is already possible, by sending a logic signal to the door circuit.
Rather than power, you just have to get creative with Logic systems: It already can be done using the various logic gates, I am pretty sure.

**Comment by tsunamayo** [comment]
So there wont be any link for energy (there might be for other component though, like fuel or ammo). But it will be possible to desactivate each component in order to manage ship energy balance, a la Elite or FTL. For Door locking ect it is possible to design a kill switch with a AND logic gate. 
Thats it! Cheers
