### ISSUE TITLE
[Experimental] Painting freeform blocks on child entities crashes multiplayer

### ISSUE THREAD

**Issue by ProPeach** [tsunamayo/Skywanderers#522]
Painting the incredible new freeform block causes all other players to be unable to interact with the world, however the player who painted the block remains unaffected. This only seemed to happen when the freeform block was placed on a child entity.

This is the output log of the player who painted the block, and didn't crash (Me)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1588094/output_log.txt)

This is the output log of the player who crashed as a result of the freeform block being painted (Khowhl)
[output_log.txt](https://github.com/tsunamayo/Skywanderers/files/1588100/output_log.txt)

**Comment by schlid** [comment]
More specifically this occurs on child entities on hinges, not rotators.

**Comment by JRL101** [comment]
confirmed, Hinges with freeform blocks on can cause crashes from being painted or edited.
Unable to pinpoint a more exact cause, as to build anything more, the world requires a wipe each time.
This bug can also cause the game to still run but nothing can be painted/edited/removed/added/linked/flown/controlled.

Just from that type of bug out i feel it has something to do with the freeform blocks edit mode. Since the edit mode takes control away from the players ability to place blocks and bricks.

**Comment by tsunamayo** [comment]
Hello, yes indeed freeform cannot work with hinge in the current implementation. I have desactivated the option to build them on hinge as they are supposed to replace them in a lot of use case. Thanks!
