### ISSUE TITLE
Lighting brightness

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#554]
More of a nitpick that an issue, but lighting seems to be much brighter than before. Could possibly be they spawn at a higher brightness. Can be a bit blinding on existing builds. 
(New and old:) 
![image](https://user-images.githubusercontent.com/29961381/36358630-3dfbec36-1509-11e8-9702-53351c3f3dd9.png)

**Comment by tsunamayo** [comment]
Yes this is by design. I agree you will definitely need to tweak light at some place.
The reason is I always find it difficult to light well a room without having to spam light block everywhere. (like every 2-3m). Now with the new light in my experience you can get away with half the light. If you want a dimmer light you can either: paint it gray or any darker color, or send the light a value like 0.5.
Hope it is not too painful. 
Awesome hangar btw!
Cheers
