### ISSUE TITLE
Missiles ignore shields [18w11a]

### ISSUE THREAD

**Issue by etn249** [tsunamayo/Skywanderers#581]
When shooting missiles at a ship with a shield, the missiles go through the shield as if it was not there and 
directly damage the blocks.

This allows to rapidly destroy any ship no matter what strength its shield has.

**Comment by tsunamayo** [comment]
Hi, this is by design, missile will get through shields like in many games, to add depth to the ship design and combat. There will be other active/passive defense system against them. Obviously this might change depending on balance issues. Beam is not working but should though, I just wanted to wait for the weapon refactoring. Cheers
