### ISSUE TITLE
BUG - Mechs

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#624]
all the western style turret controls seems to be broken/ not working on the prefab mech supplied with a new world

**Comment by Senakysam** [comment]
That mech used the old turret system. It was broken after the new system replaced the old one.

**Comment by tsunamayo** [comment]
@Senakysam I tried to fix it but I am not sure to remember how the setting was made. Did you used two turret computer (one for pilot one for second turret?)

**Comment by Senakysam** [comment]
Yeah, one turret computer each, but they're buried in the waist somewhere under armor and I didn't plan ahead and make them accessible. I can look at it again on my world and see if I can fix it. 

Also, the little blue mech in front of the spawn building seems to be missing a turret core as well, so that will need a quick fix. Thankfully nothing it covered, so it's super easy.
