### ISSUE TITLE
2x1 microblock grid can't be broken from the front

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#655]
![image](https://user-images.githubusercontent.com/31857052/37942276-3e2edfec-316a-11e8-8dcd-a2512c43973c.png)
When placed, looking at this block from the front (where you're able to see the two grey dots) will go straight through to the blocks behind it. You can only destroy it by looking through the untextured side behind it.

**Comment by Napther** [comment]
I will second this bug, and add that the 1x4 Studgrid also exhibits this behaviour. Have to move the camera below the plane of placement in order to select its hitbox. Bricks can be placed on top as-normal.

![image](https://user-images.githubusercontent.com/33023316/37996948-5b2f3086-3211-11e8-81e7-cbbe9702952f.png)

![image](https://user-images.githubusercontent.com/33023316/37996954-60ba1d86-3211-11e8-88be-af6201273af3.png)

**Comment by schlid** [comment]
Seems to occur with every block grid that is 1 grid wide in at least one dimension, meaning the 2x2 block grid and 4x4 block grid is fine.

**Comment by Rizzo911** [comment]
This is also occurring on sticker blocks.

**Comment by tsunamayo** [comment]
This issue should be fixed now. Thanks!
