### ISSUE TITLE
[Bug] Entering camera raw makes purple lines.

### ISSUE THREAD

**Issue by Varraka** [tsunamayo/Skywanderers#667]
Heya, tiny bug, noticed entering a camera in a raw state produces static bright purple lines and they dont look like targeting recticles. XD Entering the same camera through piloting system works just fine with no wierd lines present. Took a pic of it incase that helps...Raw:
![purple lines](https://user-images.githubusercontent.com/37700342/38041637-49c968d8-3280-11e8-8628-79d2406d735e.jpg)

**Comment by Dwarf-LordPangolin** [comment]
I suspect those lines are the same lines that highlight the camera's outline when mousing over it. I'm guessing that since your character is still mousing over the camera, it's still drawing the highlight lines.

![20180328153022_1](https://user-images.githubusercontent.com/33041786/38054579-074ff770-329d-11e8-936b-31fe4d1c1f73.jpg)

**Comment by tsunamayo** [comment]
Issue is now fixed, cheers!
