### ISSUE TITLE
SUGGESTION - Old blocks

### ISSUE THREAD

**Issue by Mellcor** [tsunamayo/Skywanderers#677]
please re enable the old blocks that were removed from the build menu when freeform blocks were added
currently in its state, freeform dose not do what i used these other blocks for and i found them easier to use as well as looking better

please re enable them, there is no reason why we cant have them and freeform

**Comment by tsunamayo** [comment]
Reason is I want to simply the codex and not have an explosion of the number of shapes... Thanks

**Comment by Mellcor** [comment]
but you said by design you have said that freeform cant be used on contantly spinning rotors and apparently it cant be used on hinges either, so by doing this you have then limited what people build
a few of my builds in progress had alot of parts on constantly spinning rotors and hinges and now i am unable to contiunue them and basicly have to restart due to the limitations

**Comment by Napther** [comment]
>  freeform cant be used on contantly spinning rotors and apparently it cant be used on hinges either,

You havent been inventive enough: 
![image](https://user-images.githubusercontent.com/33023316/38169167-a787ce7e-355a-11e8-9602-444e77551cd4.png)
When you come from a game of exploits, you get pretty good at spotting niche-uses of game behaviours. Added FFB to a hinge with heavy slider as the Proxy

**Comment by Mellcor** [comment]
@Napther yes there are ways around it, tho that just adds to my main point that im trying to make, tsuna is always aiming to make things more logical/easier to use.
it is neither of those things if you need to use a workaround to do something 

https://cdn.discordapp.com/attachments/416013956331601930/429292809544007680/progress.mp4

**Comment by Napther** [comment]
Have you heard of what a Blocks codex is? remember there are a limited amount of "values" within a game. And Weird things can start happening with these values interacting and potentially creating edge-case bugs.

While yes, the old blocks were quicker to place down, they also occupied an ENTIRE hotbar. the FFB takes only 1 slot which means less codex hopping. Granting the FFB meant more overall flexibility. The ship pictured earlier is almost entirely FFB to get the shape just right. I suppose its a loss when you build cube-ships with little geometry...
Anyway, FFB's can be size dragged overa large area to fill blocks faster and more easily to me than the old system where you press control to add dimensions because the behaviour is always defaulted at one I'd prefer not to be the default.

**Comment by Mellcor** [comment]
yea i know about the codex, thing is the blocks are still in the game, just
not in the block menu, if i load an old build, i can use the mousewheel to
then select blocks off that build and add to my hotbar. yes i uderstand the
merits of freeform and i can appreciate the diffrent forms it brings to the
game, however i perfer things with hard edges and angles instead of curves.
all im saying is give us the option to choose how we want to build, not
force us to build 1 way.
