### ISSUE TITLE
[EXPERIMENTAL] Using a Switch linked to a holo-projector, while holding a Holo-projector will create a Holo-stack.

### ISSUE THREAD

**Issue by Napther** [tsunamayo/Skywanderers#700]
https://puu.sh/zXMxe/d522d88b46.mp4

As titled.

**Comment by talrey** [comment]
I can confirm this is happening to me as well, even from several blocks away. Also happens on switches linked into the switch linked to the projector.

**Comment by tsunamayo** [comment]
I will remove that stack mecanism, that was a stupid idea... Thanks

**Comment by talrey** [comment]
The stacking mechanism is a great idea, it's so much easier and simpler than fiddling with a Scale setting in a menu! This is a really specific bug, and to be honest it's such a minor thing that I wouldn't remove the feature because of this unless there's really no way to eventually fix it. Of course, it's up to you in the end...

**Comment by tsunamayo** [comment]
Okay I fixed this one, but I am still scratching my head on what to do with this stack mechanism. Thanks

**Comment by tsunamayo** [comment]
Had to change the shape of the brick btw for technical reasons.
