### ISSUE TITLE
placing colored blocks

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#717]
Before the multitool update you could right click a color of paint and all blocks you place would be that color, this no longer works.

**Comment by oojimaflip** [comment]
I think taking the default colour mechanism out of creative was a bad idea.

**Comment by schlid** [comment]
Tsuna intended to remove this _as he explained in the devlog_ however being able to shift click a colour in the Q paint menu to select a default colour would be nice.

**Comment by JRL101** [comment]
Love the tool so far, but when the patch released the "change all blocks to color" feature was still working, but during my last game play it wasnt working. So im not sure this was an on purpose removal. Unless Tsuna intends a different key combo for colouring all blocks, or maybe a large area spray/fill function.

**Comment by schlid** [comment]
@JRL101 In the **_devlog_** he states he removed it as it won't be in line with survival; most likely due to the fact he probably doesn't want to have lots of painted blocks as different items in the inventory, instead having bluish grey as the default colour for armour and then you can either paint it, or unpaint it.

However being able to select a colour to immediately paint the blocks you placed would be a way of handling this and keeping it within the bounds of survival.

**Comment by tsunamayo** [comment]
Yes I am removing this feature as it was misclick prone (it happened to me all the time), but most importantly for survival and crafting each block will have its basic color (not bluish gray), that will reflect the block composition. Sorry for the upset but as I progress I will remove things there and there... Thanks
