### ISSUE TITLE
[Experimental] 18w15 Thruster blocks cannot be drag-built

### ISSUE THREAD

**Issue by talrey** [tsunamayo/Skywanderers#724]
I really like the new method of building multiple blocks at once, it's quite helpful to be able to change the drag axis so easily.

That being said, I've been unable to get it working with Thruster blocks. I can make the blue arrows appear, but changing the drag axis has no effect and the white preview volume box stays at the size of one block.

**Comment by Napther** [comment]
Thruster blocks have a rotation quality, by dragging around you change its facing direction. Similarly the Storage block, Hyperdrive, etc cannot be dragged and multi-placed down.

**Comment by tsunamayo** [comment]
Okay I see, it is a manual flag so dont hesitate to report any block/shape missing. For now for rotating blocks you need to press SHIFT, but I am not a big fan of that. 

On that topic, what you guys would think of rotating block with Q (and E) before pressing LMB, and then dragging to get the multi-block placement? I was against at first because such solution would require constantly showing a block preview, and I find that gets in the way of understanding your build in other game, but maybe I could work that out with a minimalist preview.
Thinking of that as I want to generalize freeform, so you could create a freeform of a wedge on the fly with the drag feature. It could also do wonder with bricks, like instead of seeing build with 100s of mini brick on top of each other and giving me a hearth attach, people could just drag a larger one (in 3d, not just a plane), which would be 100x more efficient on the rendering and collisions.

**Comment by talrey** [comment]
I think rotating the original block and pressing shift to "lock it in" and begin dragging out is fine. Setting the rotation before you place down the block is how Robocraft does it, and Skywanderers' rotation preview is much more elegant and useful (especially with the scroll wheel to change the rotation plane!).

About the Freeform slope drag: That would be fantastic and I'm sure it would be well-received by a lot of builders.

About bricks: I'm not sure I understand. Are you proposing a freeform brick? I think the community Discord would be ecstatic about that, beyond description. There would definitely be heart attacks if _that_ was announced, but they'd be from sheer excitement!

**Comment by tsunamayo** [comment]
This was fixed a few versions back. Thanks
