### ISSUE TITLE
[Experimental] Multitool

### ISSUE THREAD

**Issue by ThatFungiNub** [tsunamayo/Skywanderers#736]
The new Multi tool has just made more issues than it's fixed in my case at least... 

I place one block and it places 10 downwards (which I didnt ask for) and mirror blocks also hate the tool, it either deletes nothing on the other side, or deletes half of my ship without my asking, pretty damn infuriating

**Comment by Napther** [comment]
Step 1) Dont throw the mouse around while building - this will place many blocks

Step 2) Dont press Shift or the otherwise bound key for multi-delete. That is how you destroy a build in moments

step 3) Save a new WIP/LOG file of BPs because you can never have too many backups (same as F1 world saves need to be incessantly pressed)

Step 4) the mirror issue is already reported, and will be fixed in 18w16 experimental version (I believe)

Step 5) check which button is linked with the paints menu in keybinds. This is the button that can effect multi-place.

**Comment by ThatFungiNub** [comment]
I'm not throwing the mouse around while building... like who the hell in their right mind builds like that... 

If I don't press shift it won't delete the mirrored half so how am I meant to do anything, but alas. Basically what I'm trying to say is Step 1 and Step 2 you've given me are pretty useless

**Comment by tsunamayo** [comment]
Hi, all these issues have been reported, the mirror is already fixed and the build one will be. If it is too deal breaking for now I suggest you do not use experimental. Thanks
