### ISSUE TITLE
[Suggestion] Bring back Shift+click per brick

### ISSUE THREAD

**Issue by Tomatart** [tsunamayo/Skywanderers#791]
### Short Description of the issue:
Shift clicking now breaks all bricks in a 1m area.
...

### Steps to reproduce the issue:
Shift click while aiming at a single brick, it will break all bricks in a 1m area
...

### Environment
- Skywanderers version: Experimental
- Graphics Card: GTX 1070

### Additional information:
I would like for it to go back to the way it was when shift clicking would only break 1 brick (the one you are aiming at)
_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by schlid** [comment]
Although he mentioned this was intended some time ago, I do believe it's more annoying than good, and can often undo a lot of work by mistake, and without any undo tool currently I believe should be reverted.

**Comment by tsunamayo** [comment]
Okay, so I guess you deleted a whole voxel several time because of old habits right? (and then hate me for that ^^) The fact that you need to press shift make it less mistake prone, like you have to be willing to do a bulk delete at first.
Then if I revert it it means that I scrap the bulk delete?
Thanks

**Comment by schlid** [comment]
It's not so much being frustrated with the change, more that there are very few scenarios where it'd be applicable to mass delete microblocks. Since you often use them at a small scale, or for detail you'd often only want to remove a small amount, and being able to shift click each individual microblock to insta delete instead of everything in the 1m^2 including full blocks - (freeform with bricks on top causes even more issues)

**Comment by Tomatart** [comment]
Its not that, its that i much preferred being able to instantly delete a
brick, rather than having to hold click.

This also happens with stickers as well, shift breaking stickers breaks the
whole 1m area

**Comment by tsunamayo** [comment]
Actually this suggestion has been implemented for quite some time... Thanks!
