### ISSUE TITLE
Suggestion - only remove the dual and quad links from the codex to begin with.

### ISSUE THREAD

**Issue by schlid** [tsunamayo/Skywanderers#809]
After watching your most recent devlog, regarding the upcoming link tool, I noticed you said you'll be removing the dual and quad links entirely and also replacing the delay blocks. Would it be possible to just phase them out of the codex like you have done with gravity blocks, weapons tables, and the other hull shapes that were removed in lieu of freeform.

Otherwise it's going to damage the creations many people have made, and some spent hours on for example timed sequences like the landing gear on my ship. https://clips.twitch.tv/SpookyFurryCakeWOOP 

(I hope this post and my concerns didn't come across as selfish, but for any somewhat complex logic circuit it'd require it to be completely rebuilt, and since most people who've built circuits that complex most have somewhere to stow all the logic blocks already then it shouldn't be an issue leaving them there, until crafting and survival gameplay is more relevant.)

Also worth tagging on the end - If the mix gates and constants are turned into a 1x1 stud, then you wouldn't be able to potentially modify the "constant values" in the white nodes are there would be no way to distinguish one of multiple inputs in to a 1x1 stud from another.

**Comment by schlid** [comment]
Upon further thought, a constant could be condensed to a 1x2 piece with a data input node on the top in the middle. 
![image](https://user-images.githubusercontent.com/31857052/40545573-3aa6ceb4-6024-11e8-91bd-9f54cf15227b.png)
(The off grid location of the central node is to help distinguish this gate from a mix gate.)

A mix gate could also be condensed into a 1x2 piece with the two data input nodes above each stud. This would allow room between the two nodes to select the main area of the block to draw an output. As there is more free space on the constant this isn't an issue to consider.
![image](https://user-images.githubusercontent.com/31857052/40545961-9fbc9648-6025-11e8-905a-5a05edfc7fe0.png)

Although the constant wouldn't change in size, it would be more fluid with the other new logic blocks and their "compacted" aesthetic.
 
Similarly, a router could be compacted to a 1x2, with red nodes for both outputs and inputs going into the main mass of the block. Being able to customise the "edge" in a router too so it isn't just centered on 0.5 would be incredibly useful too, but this post isn't meant to be a wishlist :P

**Comment by talrey** [comment]
I use the shape of gates for visual flow, so I can see what the circuit is doing without even needing to see the connections. I'll be sad to see the Quad and Dual Links go because of that, but I acknowledge that there's a huge amount of space to be saved by doing so - and the new preview for links looks really good!

The game has always come with a big warning from Tsuna saying "Pre-Alpha, subject to change", change is going to happen and it's not always going to be compatible with old designs. This was bound to happen at some point, however inconvenient it may be.

I'm not sure how much work it would be, but might I suggest including a conversion from the old style to the new? The Quads and Duals maintain lists of what they're linked to, it might be possible during the loading of a ship to transfer the link trees to whatever was the input to the Dual / Quad. Again, I'm not sure how difficult that would be in practice, and how much time it would add to ship loading (hopefully it would be a one-time conversion to the new format), but it is a possible solution.

**Comment by tsunamayo** [comment]
Hi, amazing mechanism btw ;-) !
So I will try to keep as much as I can for a bit so you can convert your ship to the new design.
But at one point I will want to get rid of the old code as the new system is really too different, I cant afford to maintain two codebases at once, big simplification of the code are necessary. Sorry for that but yeah game is pre-alpha and I want to do all the changes I feel are important before I go on steam, after it will be too late!
Yeah I grew liking the aesthetic of the command panels ^^, but that shouldnt prevent us from making improvements.
Speaking of which I am also considering making a big change to the way the logic works (not just the link), I will think about that for a bit and maybe start a discussion soon, I am not sure yet I need more thinking. I feel if I ever want to do that that now would be the right time so you guys dont have to redo logic again and again.
Cheers
