### ISSUE TITLE
Blocks and bricks missing backfaces

### ISSUE THREAD

**Issue by Breezebuilder** [tsunamayo/Skywanderers#948]
### Short Description of the issue:

The models of some blocks and bricks do not have backfaces, causing a broken appearance.
All models with problems are as follows.

1. Light (both textures)
1. Light Brick (both textures)
1. Laser Sensor (both emitter and receiver)
1. Target Computer, Hovercraft Core and Mech Core
1. Slider (flat model only; Angled Slider is correct)
1. Button (flat model only; Angled Button is correct)
1. Switch (flat model only; Angled Switch is correct)
1. Hinge (smallest 90° hinge only; other hinges are correct)
1. Rotating Brick (smallest rotator only; other rotators are correct)
1. Fence
1. Panel (flat model only; Bevelled Panel is correct)
1. Panels B, C, D, E, F

![backfaces](https://user-images.githubusercontent.com/28330882/46579435-64fef580-ca5d-11e8-9144-ef96a71effb3.png)

### Environment
- Skywanderers version: revengeoftheclip v2

**Comment by Xerma** [comment]
I'm thinking them having the backface missing is intentional to the point where the game should run a bit faster but the faces remain missing after the surface they were placed on is deleted. 

Systems were causing a whole lot of lag due to every face rendering but now I don't see any face that should be hidden.

**Comment by Breezebuilder** [comment]
All models being replaced, issue irrelevant now.
