### ISSUE TITLE
Engine Trails - Maybe Remove?

### ISSUE THREAD

**Issue by Rizzo911** [tsunamayo/Skywanderers#952]
### Short Description of the issue:

So I like the idea of engine trails, but I seem to constantly run into issues with how they display on most ships. They seem good for fighters, but often give me issues in large builds, or where you want to use an engine's built in ability to glow when flying as an effect. 9/10 they don't work right, come from the wrong part of the ship (especially since we need a lot of engines for large ships). I much prefer the older style flying dot/stars feeling for movement and was a lot more generic across ship builds. 

### Steps to reproduce the issue:
- Add a ton of engines to a large ship
- Segment them to protect them to have redundant systems  EEEE B EEEE B EEEE
- OR mount them in an odd direction (forward or sideways) as an effect. 

### Environment
- Skywanderers version: 18w24a

### Additional information:

![20181010000107_1](https://user-images.githubusercontent.com/33043997/46713144-ce7c3100-cc22-11e8-96a2-4742c07f66ee.jpg)
![20181010000122_1](https://user-images.githubusercontent.com/33043997/46713151-d89e2f80-cc22-11e8-89eb-f451eb2277a4.jpg)

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\TsunamayoCorp\Skywanderers\`

**Comment by Garrett-C** [comment]
I don't know, that looks pretty cool

**Comment by Breezebuilder** [comment]
You might be in the minority of players who don't like the appearance of them, I'm afraid.
Since it's a purely visual effect, it might be possible a toggle could be added in the graphics menu.  The trails can come in handy when chasing a ship while dogfighting, but if players are okay with losing this advantage, I don't see why not.

**Comment by Rizzo911** [comment]
@Breezebuilder, yeah I like them for some things but all of my large builds have some issue like this. It would be cool if we could just toggle them on the engine itself. If radar is implemented, then trails will be obsolete because you can just follow your locked target with a HUD.

**Comment by ProPeach** [comment]
Looks like the issue arises when the engines are placed sideways like on your engine nacelles, a toggle would work wonders. 
Equally, a light block/panel/brick that gave the same beautiful glow as the engines would also solve the issue, and would make far more sense than using engine blocks just for their aesthetic.

**Comment by tsunamayo** [comment]
Trail are really problematic indeed, but I really like the look of them, especially with the new art style. There is a few issue not really related to trail, like you using engine for decoration purpose. I will make some change so that it wont be interesting for the player to do so (it would be waste of energy basically), and add a glow block replacement. I keep you posted.

**Comment by ProPeach** [comment]
Thanks for the glow blocks! Would it be too much to ask for them in brick form too? Or a glow "paint" might fit in better with your material paint idea

**Comment by tsunamayo** [comment]
So I removed the trail for now, I would to put them back in the future but I will have to develop a custom solution for my need. Thanks
