### ISSUE TITLE
Can't pause while controlling ship / sitting in seat

### ISSUE THREAD

**Issue by Bejasc** [tsunamayo/Skywanderers#99]
Sitting in default speeder - cannot pause the game by pressing escape. Have to get out of the speeders seat before pausing will do anything

**Comment by tsunamayo** [comment]
By design. Do you think it is crappy / illogical?

**Comment by Bejasc** [comment]
It did frustrate me a little 

⁣Sent from Blue ​

**Comment by tsunamayo** [comment]
Okay I will do a mini survey to see if I put that in my to do list.

**Comment by ForsakenHarmony** [comment]
should at least exit controls if it doesn't pause

**Comment by tsunamayo** [comment]
Pressing Escape key will indeed exit control.

**Comment by ForsakenHarmony** [comment]
no it doesn't?

**Comment by PsyCommando** [comment]
Tbh, I feel its illogical, because you lose the ability to access options while piloting. And since piloting will probably be a big part of the game its not very practical. Plus leaving the cockpit each times you want to access options runs the risk of falling off the vehicle and being stranded in space. Like last time I wanted to change an option ^^;

**Comment by DarianLStephens** [comment]
Heck, all I wanted to do was reply to a message on discord, but I couldn't even do that without spamming alt+tab until it stuck or opening the steam overlay. It really is frustrating to not be able to easily access any other part of your computer because of an arbitrary restriction ingame.
It's my personal opinion that the pause menu should never be restricted, because it's meant to give you a way to detach yourself from the game temporarily, hence 'Pause'.

**Comment by tsunamayo** [comment]
This will now become possible in the upcoming update - I just added the feature. Thanks a lot for your feedback guys! Cheers
