### ISSUE TITLE
[SUGGESTION] Update the "Stable" Branch

### ISSUE THREAD

**Issue by Womble-TC** [tsunamayo/Skywanderers#997]
Since the two most up-to-date builds can be un-playable at times (especially in terms of saving/loading), would it be possible for the "stable" build of skywanderers to be updated to something similar to "legacy"? This would allow people to have a reasonably new build to use (the current "stable" is before the introduction with new logic), without having to experience the bugs and current brokenness of the two latest experimental builds.

**Comment by Garrett-C** [comment]
Yeah I agree. If the stable build was updated to a build like legacy but with a way to load the new blueprints I think it would be beneficial. I know that myself and several others have been put off from playing due to the most recent build. Several of us have been annoyed by issues like the inability to easily start a new build. If we had a stable build with the new build system then we could at least fall back on that.

**Comment by tsunamayo** [comment]
Now default is the most up to date, and should be hopefully a lot more stable than what we had back in day! Cheers
